
--31862 NOAC Data Incorrectly Stored in Database
DROP TABLE HHS_CDC_HR.ATC_NATURE_OF_ACTION;

CREATE TABLE HHS_CDC_HR.ATC_NATURE_OF_ACTION
(
	CASE_ID              NUMBER(10) NOT NULL ,
    SEQ                  INTEGER NOT NULL,
	NOAC                 VARCHAR2(400) NULL ,
	FRST_AUTH            VARCHAR2(400) NULL ,
	SCND_AUTH            VARCHAR2(400) NULL ,
	ZLM_DSCRPTN          VARCHAR2(4000) NULL 
);


CREATE UNIQUE INDEX XPKATC_Nature_of_Action ON HHS_CDC_HR.ATC_NATURE_OF_ACTION
(CASE_ID   ASC, SEQ ASC);


ALTER TABLE HHS_CDC_HR.ATC_NATURE_OF_ACTION
	ADD CONSTRAINT  XPKATC_Nature_of_Action PRIMARY KEY (CASE_ID, SEQ);
    
    
SELECT *
FROM HHS_CDC_HR.ATC_NATURE_OF_ACTION
WHERE CASE_ID = 1140
;