
--#222985 DEV - Add two DB columns to Recruitment table
ALTER TABLE HHS_CDC_HR.RECRUITMENT
ADD SLOT_RQSTD           VARCHAR2(10) NULL
;

ALTER TABLE HHS_CDC_HR.RECRUITMENT
ADD JSTFCTN_NOT_RCVNG_SLOT VARCHAR2(4000) NULL
;

--223008 Rearrange Fields on the ATC tab
ALTER TABLE HHS_CDC_HR.ATC_COMPENSATION
DROP COLUMN LOCALITY;

ALTER TABLE HHS_CDC_HR.ATC_COMPENSATION
DROP COLUMN REMARKS;

ALTER TABLE HHS_CDC_HR.ATC_COMPENSATION
ADD PRIOR_REMARKS VARCHAR2(4000) NULL
;

ALTER TABLE HHS_CDC_HR.ATC_COMPENSATION
ADD PRIOR_YR VARCHAR2(20) NULL
;

ALTER TABLE HHS_CDC_HR.ATC_COMPENSATION
ADD PRIOR_LCTN VARCHAR2(400) NULL
;

ALTER TABLE HHS_CDC_HR.ATC_PERSONNEL_ACTION
ADD DT_WRKD_LST_APPNTMNT_FROM VARCHAR2(20) NULL
;

ALTER TABLE HHS_CDC_HR.ATC_PERSONNEL_ACTION
ADD DT_WRKD_LST_APPNTMNT_TO VARCHAR2(200) NULL
;

--SELECT * FROM ATC_COMPENSATION WHERE CASE_ID = 1148;
