SELECT XMLTYPE.GETCLOBVAL(FIELD_DATA) FDATA
FROM TBL_FORM_DTL
WHERE PROCID = 26153;

/*
UPDATE RLVNTDATA
SET VALUE = NULL
WHERE PROCID = 26153
AND RLVNTDATANAME NOT IN ('procId', 'wihmode', 'cdcEmailDisclaimer', 'adminEmailAddress');
*/

SELECT RLVNTDATANAME, VALUE, DISPVALUE
FROM RLVNTDATA
WHERE PROCID = 26153
AND RLVNTDATANAME NOT IN ('procId', 'wihmode', 'cdcEmailDisclaimer', 'adminEmailAddress')
ORDER BY RLVNTDATANAME;

--Generate process variable XML elements
SELECT '<' || RLVNTDATADEFNAME || ' />' AS ProcessVariable
FROM BizFlow.RLVNTDATADEF
WHERE PROCDEFID = (SELECT PROCDEFID
        FROM PROCDEF
        WHERE ISFINAL = 'T'
        AND ENVTYPE = 'O'
        AND NAME = 'Triage'
        )
AND RLVNTDATADEFNAME not in ( 'wihmode', 'nullString' )
ORDER BY RLVNTDATADEFNAME
;
        
SELECT * --RLVNTDATANAME, VALUE, DISPVALUE
FROM RLVNTDATA
WHERE PROCID = 722
AND VALUETYPE = 'P'
AND RLVNTDATANAME = 'higherSupervisor'
;

SELECT PD.NAME AS PROCDEFNAME, AD.NAME AS ACTNAME, AD.TYPE --PD.PROCDEFNAME--, AD.NAME ANAME
FROM ACTDEF AD
    JOIN PROCDEF PD ON PD.PROCDEFID = AD.PROCDEFID
WHERE PD.NAME = 'Appointment'
AND PD.ISFINAL = 'T'
AND ENVTYPE = 'O'
AND AD.TYPE = 'S'
ORDER BY PD.PROCDEFID
;


SELECT * 
FROM BIZFLOW.MEMBERINFO
WHERE ROWNUMBER < 100;
