
--Generate process variable XML elements
SELECT '<' || RLVNTDATADEFNAME || ' />' AS ProcessVariable
FROM RLVNTDATADEF
WHERE PROCDEFID = (SELECT PROCDEFID
        FROM PROCDEF
        WHERE ISFINAL = 'T'
        AND ENVTYPE = 'O'
        AND NAME = 'Appointment'
        )
AND RLVNTDATADEFNAME != 'wihmode'
ORDER BY RLVNTDATADEFNAME
;
        
SELECT * --RLVNTDATANAME, VALUE, DISPVALUE
FROM RLVNTDATA
WHERE PROCID = 722
AND VALUETYPE = 'P'
AND RLVNTDATANAME = 'higherSupervisor'
;

SELECT PD.NAME AS PROCDEFNAME, AD.NAME AS ACTNAME, AD.TYPE --PD.PROCDEFNAME--, AD.NAME ANAME
FROM ACTDEF AD
    JOIN PROCDEF PD ON PD.PROCDEFID = AD.PROCDEFID
WHERE PD.NAME = 'Appointment'
AND PD.ISFINAL = 'T'
AND ENVTYPE = 'O'
AND AD.TYPE = 'S'
ORDER BY PD.PROCDEFID
;

