create or replace PROCEDURE "HHS_CDC_HR"."SP_UPDATE_NAMEDACTION_TBLS" 
(
  I_PROCID IN NUMBER 
) 
    ------------------------------------------------------------------------------------------
    --  Procedure name	    : 	SP_UPDATE_NAMEDACTION_TBLS
    --	Author				:	Taeho Lee <thee@bizflow.com>
    --	Copyright			:	BizFlow Corp.	
    --	
    --	Project				:	HHS CDC HR Workflow Solution - EWITS 2.0
    --	Purpose				:	Insert/Update Named Action tables with XML document in TBL_FORM_DTL.FIELD_DATA
    --	
    --  Example
    --  To use in SQL statements:
    --
    -- 	WHEN		WHO			WHAT		
    -- 	-----------	--------	-------------------------------------------------------
    -- 	10/25/2018	THLEE		Created
    -- 	-----------	--------	-------------------------------------------------------
IS
-------- COMMON
    V_RECCNT                            INTEGER;

-------- FORM DATA
    V_FD_ID                             NUMBER(20);
    V_FD_PROCID	                        NUMBER(10);
    V_FD_ACTSEQ                         NUMBER(10);
    V_FD_WITEMSEQ                       NUMBER(10);
    V_FD_FORM_TYPE                      VARCHAR2(50);
    V_FD_FIELD_DATA	                    XMLTYPE;
    V_FD_CRT_DT	                        TIMESTAMP;
    V_FD_CRT_USR                        VARCHAR2(50);
    V_FD_MOD_DT	                        TIMESTAMP;
    V_FD_MOD_USR	                    VARCHAR2(50);
-------- HR_CASE
    V_CASE_ID                           NUMBER(10);
    V_CASE_CREATOR_NM                   VARCHAR(100);
    V_CASE_CREATION_DT                  TIMESTAMP;
-------- APPOINTMENT
	V_APT_RQST_TP              VARCHAR2(100);
	V_APT_HIRING_METHOD        VARCHAR2(20);
	V_APT_ADMIN_CD             VARCHAR2(20);
	V_APT_ORG_NM               VARCHAR2(200);
	V_APT_SHRD_CERT            VARCHAR2(200);
	V_APT_VA_NO                VARCHAR2(200);
	V_APT_CERT_NO              VARCHAR2(200);
	V_APT_AREA_OF_CONSIDERATION VARCHAR(200);
	V_APT_NON_COMP_TYPE        VARCHAR2(200);
	V_APT_JOB_REQ_NO           VARCHAR2(100);
	V_APT_POS_BSD_MGMT_SYS_NO  VARCHAR2(100);
	V_APT_SO_NM                VARCHAR2(100);
	V_APT_SO_EMAIL             VARCHAR2(100);
	V_APT_CIO_ADMN_NM          VARCHAR2(100);
	V_APT_CIO_ADMN_EMAIL       VARCHAR2(100);
	V_APT_HRO_SPC_NM           VARCHAR2(100);
	V_APT_HRO_SPC_EMAIL        VARCHAR2(100);
	V_APT_CLA_SPC_NM           VARCHAR2(100);
	V_APT_CLA_SPC_EMAIL        VARCHAR2(100);
	V_APT_HRO_SPC_ASSSTNT_NM   VARCHAR2(100);
	V_APT_HRO_SPC_ASSSTNT_EMAIL VARCHAR2(100); 
-------- ATC_VALIDATION
	V_VLD_STFFNG_NEED_VLDTD    VARCHAR2(100);
	V_VLD_JST_NOT_STFF_NEED_VLDTD VARCHAR2(4000);
	V_VLD_PBMS_FUND_CNFRMD     VARCHAR2(100);
	V_VLD_JST_NOT_PBMS_FUND_CNFRMD VARCHAR2(4000);
	V_VLD_HRNG_OPTNS_GID_RVWD  VARCHAR2(100);
	V_VLD_JST_NOT_HRNG_OPTNS_GID VARCHAR2(4000);
	V_VLD_SLT_RQSTD            VARCHAR2(100);
    V_VLD_JST_NOT_SLT_RQSTD VARCHAR2(4000);  
-------- ATC_POSITION_INFO
	V_POSINFO_POS_TTL              VARCHAR2(4000);
	V_POSINFO_PAY_PLAN             VARCHAR2(4000);
	V_POSINFO_SERIES               VARCHAR2(4000);
	V_POSINFO_GRADE                VARCHAR2(100);
	V_POSINFO_LOCATION             VARCHAR2(400);
	V_POSINFO_LAST_NM              VARCHAR2(200);
	V_POSINFO_FIRST_NM             VARCHAR2(200);
	V_POSINFO_MIDDLE_INITIAL       VARCHAR2(200);
	V_POSINFO_CNTRY_OF_CTZNSHP     VARCHAR2(200);
	V_POSINFO_VISA_ASSSTNC_RQRD    VARCHAR2(200);
-------- ATC_NATURE_OF_ACTION
	V_NATROFACTN_NOAC                 VARCHAR2(400);
-------- ATC_PERSONNEL_ACTION
	V_PACT_EFFCTV_DT            VARCHAR2(20);
	V_PACT_NTE_DT               VARCHAR2(20);
	V_PACT_VETS_PRFRNC          VARCHAR2(400);
	V_PACT_INT_WRKD_LAST_APPT VARCHAR2(100);
	V_PACT_INT_WRKD_THIS_APPT VARCHAR2(100);
	V_PACT_INT_WRKD_LAST_APPT_TP VARCHAR2(10);
	V_PACT_INT_WRKD_THIS_APPT_TP VARCHAR2(10);
    V_PACT_DT_WRKD_LST_APPT_FROM VARCHAR2(20);
    V_PACT_DT_WRKD_LST_APPT_TO VARCHAR2(200);    
-------- ATC_COMPENSATION
	V_CMPNSTN_COMMON_ACCT_NO       VARCHAR2(400);
	V_CMPNSTN_FED_FSCL_YR          VARCHAR2(100);
	V_CMPNSTN_PRIOR_FED_SVC        VARCHAR2(400);
	V_CMPNSTN_HIGHEST_PRE_PAY_PLAN VARCHAR2(400);
	V_CMPNSTN_HIGHEST_PRE_GRADE    VARCHAR2(400);
	V_CMPNSTN_HIGHEST_PRE_STEP     VARCHAR2(400);
	V_CMPNSTN_HIGHEST_PRE_SALARY   VARCHAR2(400);
	--V_CMPNSTN_LOCALITY             VARCHAR2(400);
	--V_CMPNSTN_REMARKS              VARCHAR2(4000);
	V_CMPNSTN_TERM_RTNTIN_ALLWNC   VARCHAR2(400);
	V_CMPNSTN_PAY_SET_EQV_PAY_PLAN VARCHAR2(400);
	V_CMPNSTN_PAY_SET_EQV_GRADE    VARCHAR2(400);
    V_CMPNSTN_PAY_SET_STEP         VARCHAR2(400);
	V_CMPNSTN_PAY_SET_EQV_AMOUNT   VARCHAR2(400);
	V_CMPNSTN_INCENTIVES           VARCHAR2(400);
	V_CMPNSTN_MRKT_PAY             VARCHAR2(400);
	V_CMPNSTN_POST_DIFF_PER        VARCHAR2(400);
	V_CMPNSTN_POST_DIFF_STTS       VARCHAR2(100);
	V_CMPNSTN_COLA_PER             VARCHAR2(400);
	V_CMPNSTN_COLA_STTS            VARCHAR2(100);
	V_CMPNSTN_DANGER_PAY_STTS      VARCHAR2(100);
	V_CMPNSTN_PAY_CRDNTD_W_SO      VARCHAR2(400);
    V_CMPNSTN_PRIOR_YR             VARCHAR2(20);
    V_CMPNSTN_PRIOR_LCTN           VARCHAR2(400);
    V_CMPNSTN_PRIOR_REMARKS        VARCHAR2(4000);

-------- ATC_BENEFITS
	V_BNFTS_VISA_TP              VARCHAR2(400);
	V_BNFTS_EMP_ENTTLD_TO_BNFTS  VARCHAR2(100);
-------- ATC_SELECTED_BENEFITS    
	V_BNFTS_ENTTLD_BNFTS         VARCHAR2(4000);
-------- APP_TRACKING
    V_TRCK_CSO_DEPUTY_DIR_APPRVL VARCHAR2(400);
    V_TRCK_MEMO_SGND_DT         VARCHAR2(20);
    V_TRCK_ETHICS_CLRNC_STTS    VARCHAR2(100);
    V_TRCK_ETHICS_DCSN_RCVD_DT  VARCHAR2(20);
    V_TRCK_SEC_CLRNC_STTS       VARCHAR2(100);
    V_TRCK_SEC_DCSN_RCVD_DT     VARCHAR2(20);
    V_TRCK_WRK_ATH_STTS     VARCHAR2(20);
    V_TRCK_WRK_ATH_DCSN_RCVD_DT VARCHAR2(20);
    V_TRCK_CAPHR_POS_NO         VARCHAR2(100);
    V_TRCK_JOB_CD               VARCHAR2(100);
-------- APP_APPROVAL
    V_APVL_HR_ASSSTNT_NM VARCHAR2(200);
    V_APVL_HR_ASSSTNT_APPRVL_DT VARCHAR2(20);
    V_APVL_HRS_SPC_NM VARCHAR2(200);
    V_APVL_HRS_SPC_APPRVL_DT VARCHAR2(20);
    V_APVL_SR_HRS_SPC_NM VARCHAR2(200);
    V_APVL_SR_HRS_SPC_APPRVL_DT VARCHAR2(20);
    V_APVL_ADDTNL_APPRVL_NM VARCHAR2(200);
    V_APVL_ADDTNL_APPRVL_RQRD VARCHAR2(20);
    V_APVL_ADDTNL_APPRVL_EMAIL VARCHAR2(200);   
-------- POSITION_BUILD_APPROVAL
	V_POSBLD_ACTV_N_ACCRT         VARCHAR2(100);
	V_POSBLD_ALL_SIGN_OF8         VARCHAR2(100);
	V_POSBLD_CAPHR_POS_NO         VARCHAR2(100);
	V_POSBLD_JOB_CODE             VARCHAR2(100);
	V_POSBLD_BUS_ARRVD            VARCHAR2(100);
	V_POSBLD_SPRVSRY_STTS_APPRVD  VARCHAR2(100);
	V_POSBLD_FLSA_APPRVD          VARCHAR2(100);
	V_POSBLD_ADMIN_CD_APPRVD      VARCHAR2(100);
	V_POSBLD_PM_STWRD_NM          VARCHAR2(100);
	V_POSBLD_PM_STWRD_APPRVD      VARCHAR2(100);
-------- TSA_PROCESSING
	V_TSAPRC_TSA_PRCSSR_NM        VARCHAR2(200);
	V_TSAPRC_TSA_PRCSSR_APPRVL_DT VARCHAR2(100);
	V_TSAPRC_ADDL_APPRVL_RQRD   VARCHAR2(20);
	V_TSAPRC_ADDL_TSA_NM VARCHAR2(200);
	V_TSAPRC_ADDL_TSA_EMAIL VARCHAR2(200);
	V_TSAPRC_LD_TSA_NM   VARCHAR2(200);
	V_TSAPRC_LD_TSA_APPRVL_DT VARCHAR2(20);
	V_TSAPRC_DOC_SCANNED_TO_EOPF  VARCHAR2(100);
	V_TSAPRC_QLTY_ASSRNC_RVW_CMPL VARCHAR2(100);
BEGIN

    --DBMS_OUTPUT.PUT_LINE('I_PROCID=' || I_PROCID); 
    SELECT "ID",
           PROCID,
           ACTSEQ,
           WITEMSEQ,
           FORM_TYPE,
           FIELD_DATA,
           CRT_DT,
           CRT_USR,
           MOD_DT,
           MOD_USR
      INTO V_FD_ID,
           V_FD_PROCID,
           V_FD_ACTSEQ,
           V_FD_WITEMSEQ,
           V_FD_FORM_TYPE,
           V_FD_FIELD_DATA,
           V_FD_CRT_DT,
           V_FD_CRT_USR,
           V_FD_MOD_DT,
           V_FD_MOD_USR    
      FROM HHS_CDC_HR.TBL_FORM_DTL
     WHERE PROCID = I_PROCID;

    ---------- HR_CASE TABLE
    V_RECCNT := 0;
    SELECT COUNT(1)
      INTO V_RECCNT
      FROM HHS_CDC_HR.HR_CASE
     WHERE CASE_ID = I_PROCID;

    IF V_RECCNT = 0 THEN
        --DBMS_OUTPUT.PUT_LINE('INSERT INTO HHS_CDC_HR.HR_CASE');
        INSERT INTO HHS_CDC_HR.HR_CASE 
        (
            CASE_ID
            ,CASE_TP
            ,CREATOR_NM
            ,CREATION_DT
        )
        VALUES 
        (
            I_PROCID
            ,'CLASSIFICATION'
            ,V_FD_CRT_USR
            ,V_FD_CRT_DT
        );

    ELSE
        UPDATE HHS_CDC_HR.HR_CASE
           SET CASE_TP = 'CLASSIFICATION'
               ,MODIFIER_NM = V_FD_MOD_USR
               ,MODIFICATION_DT = V_FD_MOD_DT
         WHERE CASE_ID = I_PROCID;
    END IF;


-------- APPOINTMENT
    SELECT   FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'REQUEST_TYPE') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'HM_ID') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ADMIN_CD') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ORG_NAME') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'SHRD_CERT') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'VAN') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'CERT_NUM') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'POS_AOC') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'NON_COMP_TYPE') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'POS_JOB_REQ_NUM') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'PBMS_ID') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'SO_AutoComplete') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'SO_EMAIL') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'CIO_AutoComplete') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'CIO_EMAIL') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'HROS_AutoComplete') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'HROS_EMAIL') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'CLASS_SPEC_AutoComplete') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'CLASS_SPEC_EMAIL') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'HROA_AutoComplete') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'HROA_EMAIL') --
      INTO 
            V_APT_RQST_TP
            ,V_APT_HIRING_METHOD
            ,V_APT_ADMIN_CD
            ,V_APT_ORG_NM
            ,V_APT_SHRD_CERT
            ,V_APT_VA_NO
            ,V_APT_CERT_NO
            ,V_APT_AREA_OF_CONSIDERATION
            ,V_APT_NON_COMP_TYPE
            ,V_APT_JOB_REQ_NO
            ,V_APT_POS_BSD_MGMT_SYS_NO
            ,V_APT_SO_NM
            ,V_APT_SO_EMAIL
            ,V_APT_CIO_ADMN_NM
            ,V_APT_CIO_ADMN_EMAIL
            ,V_APT_HRO_SPC_NM
            ,V_APT_HRO_SPC_EMAIL
            ,V_APT_CLA_SPC_NM
            ,V_APT_CLA_SPC_EMAIL
            ,V_APT_HRO_SPC_ASSSTNT_NM
            ,V_APT_HRO_SPC_ASSSTNT_EMAIL
       FROM DUAL;

    V_RECCNT := 0;
    SELECT COUNT(1)
      INTO V_RECCNT
      FROM HHS_CDC_HR.APPOINTMENT
     WHERE CASE_ID = I_PROCID;

    IF V_RECCNT = 0 THEN
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('INSERT INTO HHS_CDC_HR.APPOINTMENT');
        INSERT INTO HHS_CDC_HR.APPOINTMENT 
        (                        
            CASE_ID
            ,RQST_TP
            ,HIRING_METHOD
            ,ADMIN_CD
            ,ORG_NM
            ,SHRD_CERT
            ,VA_NO
            ,CERT_NO
            ,AREA_OF_CONSIDERATION
            ,NON_COMP_TYPE
            ,JOB_REQ_NO
            ,POS_BSD_MGMT_SYS_NO
            ,SO_NM
            ,SO_EMAIL
            ,CIO_ADMN_NM
            ,CIO_ADMN_EMAIL
            ,HRO_SPC_NM
            ,HRO_SPC_EMAIL
            ,CLA_SPC_NM
            ,CLA_SPC_EMAIL
            ,HRO_SPC_ASSSTNT_NM
            ,HRO_SPC_ASSSTNT_EMAIL
        )
        VALUES 
        (
            I_PROCID
            ,V_APT_RQST_TP
            ,V_APT_HIRING_METHOD
            ,V_APT_ADMIN_CD
            ,V_APT_ORG_NM
            ,V_APT_SHRD_CERT
            ,V_APT_VA_NO
            ,V_APT_CERT_NO
            ,V_APT_AREA_OF_CONSIDERATION
            ,V_APT_NON_COMP_TYPE
            ,V_APT_JOB_REQ_NO
            ,V_APT_POS_BSD_MGMT_SYS_NO
            ,V_APT_SO_NM
            ,V_APT_SO_EMAIL
            ,V_APT_CIO_ADMN_NM
            ,V_APT_CIO_ADMN_EMAIL
            ,V_APT_HRO_SPC_NM
            ,V_APT_HRO_SPC_EMAIL
            ,V_APT_CLA_SPC_NM
            ,V_APT_CLA_SPC_EMAIL
            ,V_APT_HRO_SPC_ASSSTNT_NM
            ,V_APT_HRO_SPC_ASSSTNT_EMAIL
        );

    END;    
    ELSE
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('UPDATE HHS_CDC_HR.CLASSIFICATION');
        UPDATE HHS_CDC_HR.APPOINTMENT
           SET 
                RQST_TP = V_APT_RQST_TP
                ,HIRING_METHOD = V_APT_HIRING_METHOD
                ,ADMIN_CD = V_APT_ADMIN_CD
                ,ORG_NM = V_APT_ORG_NM
                ,SHRD_CERT = V_APT_SHRD_CERT
                ,VA_NO = V_APT_VA_NO
                ,CERT_NO = V_APT_CERT_NO
                ,AREA_OF_CONSIDERATION = V_APT_AREA_OF_CONSIDERATION
                ,NON_COMP_TYPE = V_APT_NON_COMP_TYPE
                ,JOB_REQ_NO = V_APT_JOB_REQ_NO
                ,POS_BSD_MGMT_SYS_NO = V_APT_POS_BSD_MGMT_SYS_NO
                ,SO_NM = V_APT_SO_NM
                ,SO_EMAIL = V_APT_SO_EMAIL
                ,CIO_ADMN_NM = V_APT_CIO_ADMN_NM
                ,CIO_ADMN_EMAIL = V_APT_CIO_ADMN_EMAIL
                ,HRO_SPC_NM = V_APT_HRO_SPC_NM
                ,HRO_SPC_EMAIL = V_APT_HRO_SPC_EMAIL
                ,CLA_SPC_NM = V_APT_CLA_SPC_NM
                ,CLA_SPC_EMAIL = V_APT_CLA_SPC_EMAIL
                ,HRO_SPC_ASSSTNT_NM = V_APT_HRO_SPC_ASSSTNT_NM
                ,HRO_SPC_ASSSTNT_EMAIL = V_APT_HRO_SPC_ASSSTNT_EMAIL
         WHERE CASE_ID = I_PROCID;

    END;
    END IF;        

-------- ATC_VALIDATION
    SELECT   FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'STF_VAL') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'STF_VAL_JUST') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'FND_CONF') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'FND_CONF_JUST') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'HIRE_GUIDE_REV') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'HIRE_GUIDE_REV_JUST') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'SLOT_REQ') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'SLOT_REQ_JUST') --
      INTO 
            V_VLD_STFFNG_NEED_VLDTD
            ,V_VLD_JST_NOT_STFF_NEED_VLDTD
            ,V_VLD_PBMS_FUND_CNFRMD
            ,V_VLD_JST_NOT_PBMS_FUND_CNFRMD
            ,V_VLD_HRNG_OPTNS_GID_RVWD
            ,V_VLD_JST_NOT_HRNG_OPTNS_GID
            ,V_VLD_SLT_RQSTD
            ,V_VLD_JST_NOT_SLT_RQSTD
       FROM DUAL;

    V_RECCNT := 0;
    SELECT COUNT(1)
      INTO V_RECCNT
      FROM HHS_CDC_HR.ATC_VALIDATION
     WHERE CASE_ID = I_PROCID;

    IF V_RECCNT = 0 THEN
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('INSERT INTO HHS_CDC_HR.ATC_VALIDATION');
        INSERT INTO HHS_CDC_HR.ATC_VALIDATION 
        (                        
            CASE_ID
            ,STFFNG_NEED_VLDTD
            ,JSTFCTN_NOT_STFFNG_NEED_VLDTD
            ,PBMS_FUND_CNFRMD
            ,JSTFCTN_NOT_PBMS_FUND_CNFRMD
            ,HRNG_OPTNS_GID_RVWD
            ,JSTFCTN_NOT_HRNG_OPTNS_GID
            ,SLT_RQSTD
            ,JSTFCTN_NOT_SLT_RQSTD
        )
        VALUES 
        (
            I_PROCID
            ,V_VLD_STFFNG_NEED_VLDTD
            ,V_VLD_JST_NOT_STFF_NEED_VLDTD
            ,V_VLD_PBMS_FUND_CNFRMD
            ,V_VLD_JST_NOT_PBMS_FUND_CNFRMD
            ,V_VLD_HRNG_OPTNS_GID_RVWD
            ,V_VLD_JST_NOT_HRNG_OPTNS_GID
            ,V_VLD_SLT_RQSTD
            ,V_VLD_JST_NOT_SLT_RQSTD
        );

    END;    
    ELSE
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('UPDATE HHS_CDC_HR.CLASSIFICATION');
        UPDATE HHS_CDC_HR.ATC_VALIDATION
           SET
            STFFNG_NEED_VLDTD = V_VLD_STFFNG_NEED_VLDTD
            ,JSTFCTN_NOT_STFFNG_NEED_VLDTD = V_VLD_JST_NOT_STFF_NEED_VLDTD
            ,PBMS_FUND_CNFRMD = V_VLD_PBMS_FUND_CNFRMD
            ,JSTFCTN_NOT_PBMS_FUND_CNFRMD = V_VLD_JST_NOT_PBMS_FUND_CNFRMD
            ,HRNG_OPTNS_GID_RVWD = V_VLD_HRNG_OPTNS_GID_RVWD
            ,JSTFCTN_NOT_HRNG_OPTNS_GID = V_VLD_JST_NOT_HRNG_OPTNS_GID
            ,SLT_RQSTD = V_VLD_SLT_RQSTD
            ,JSTFCTN_NOT_SLT_RQSTD = V_VLD_JST_NOT_SLT_RQSTD
         WHERE CASE_ID = I_PROCID;

    END;
    END IF;        	

-------- ATC_POSITION_INFO
    SELECT   FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_TITLE') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_PAY_PLAN_CODE') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_SERIES') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_GRADE_ID') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_DUTY_STATION') --
            --,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_LAST_NAME') --
            --,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_FIRST_NAME') --
            --,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_MIDDLE_INITIAL') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_CITIZEN_OF') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_VISA_ASSISTANCE_REQ') --
      INTO 
            V_POSINFO_POS_TTL
            ,V_POSINFO_PAY_PLAN
            ,V_POSINFO_SERIES
            ,V_POSINFO_GRADE
            ,V_POSINFO_LOCATION
            --,V_POSINFO_LAST_NM
            --,V_POSINFO_FIRST_NM
            --,V_POSINFO_MIDDLE_INITIAL
            ,V_POSINFO_CNTRY_OF_CTZNSHP
            ,V_POSINFO_VISA_ASSSTNC_RQRD
       FROM DUAL;

    V_RECCNT := 0;
    SELECT COUNT(1)
      INTO V_RECCNT
      FROM HHS_CDC_HR.ATC_POSITION_INFO
     WHERE CASE_ID = I_PROCID;

    IF V_RECCNT = 0 THEN
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('INSERT INTO HHS_CDC_HR.ATC_VALIDATION');
        INSERT INTO HHS_CDC_HR.ATC_POSITION_INFO 
        (                        
            CASE_ID
            ,POS_TTL
            ,PAY_PLAN
            ,SERIES
            ,GRADE
            ,LOCATION
            ,LAST_NM
            ,FIRST_NM
            ,MIDDLE_INITIAL
            ,CNTRY_OF_CTZNSHP
            ,VISA_ASSSTNC_RQRD
        )
        VALUES 
        (
            I_PROCID
            ,V_POSINFO_POS_TTL
            ,V_POSINFO_PAY_PLAN
            ,V_POSINFO_SERIES
            ,V_POSINFO_GRADE
            ,V_POSINFO_LOCATION
            ,V_POSINFO_LAST_NM
            ,V_POSINFO_FIRST_NM
            ,V_POSINFO_MIDDLE_INITIAL
            ,V_POSINFO_CNTRY_OF_CTZNSHP
            ,V_POSINFO_VISA_ASSSTNC_RQRD
        );

    END;
    ELSE
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('UPDATE HHS_CDC_HR.ATC_POSITION_INFO');
        UPDATE HHS_CDC_HR.ATC_POSITION_INFO
           SET
                POS_TTL = V_POSINFO_POS_TTL
                ,PAY_PLAN = V_POSINFO_PAY_PLAN
                ,SERIES = V_POSINFO_SERIES
                ,GRADE = V_POSINFO_GRADE
                ,LOCATION = V_POSINFO_LOCATION
                ,LAST_NM = V_POSINFO_LAST_NM
                ,FIRST_NM = V_POSINFO_FIRST_NM
                ,MIDDLE_INITIAL = V_POSINFO_MIDDLE_INITIAL
                ,CNTRY_OF_CTZNSHP = V_POSINFO_CNTRY_OF_CTZNSHP
                ,VISA_ASSSTNC_RQRD = V_POSINFO_VISA_ASSSTNC_RQRD
         WHERE CASE_ID = I_PROCID;

    END;
    END IF;

-------- ATC_NATURE_OF_ACTION 
--713-X%%Reg 351.608(d)(1)%%22%%aaa::781-0%%Reg 531.404%%111%%gggg
    DELETE 
      FROM HHS_CDC_HR.ATC_NATURE_OF_ACTION
     WHERE CASE_ID = I_PROCID;

    SELECT FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_NOACS') 
      INTO V_NATROFACTN_NOAC
      FROM DUAL;

    IF V_NATROFACTN_NOAC IS NOT NULL THEN
        --DBMS_OUTPUT.PUT_LINE('INSERT HHS_CDC_HR.ATC_NATURE_OF_ACTION');
        /*
        INSERT INTO HHS_CDC_HR.ATC_NATURE_OF_ACTION 
        (
            CASE_ID
            ,SEQ
            ,NOAC
            ,FRST_AUTH
            ,SCND_AUTH
            ,ZLM_DSCRPTN
        )        
        SELECT I_PROCID AS CASE_ID
                ,substr(V_NATROFACTN_NOAC, 1, instr(V_NATROFACTN_NOAC, '%%', 1, 1)-1) NOAC
                ,substr(V_NATROFACTN_NOAC, instr(V_NATROFACTN_NOAC, '%%', 1, 1)+2 , instr(V_NATROFACTN_NOAC, '%%', 1, 2) - instr(V_NATROFACTN_NOAC, '%%', 1, 1) - 2) FRST_AUTH
                ,substr(V_NATROFACTN_NOAC, instr(V_NATROFACTN_NOAC, '%%', 1, 2)+2 , instr(V_NATROFACTN_NOAC, '%%', 1, 3) - instr(V_NATROFACTN_NOAC, '%%', 1, 2) - 2) SCND_AUTH
                ,substr(V_NATROFACTN_NOAC, instr(V_NATROFACTN_NOAC, '%%', 1, 3)+2) COMP_LEVEL
         FROM DUAL;
        */ 

        INSERT INTO HHS_CDC_HR.ATC_NATURE_OF_ACTION 
        (
            CASE_ID
            ,SEQ
            ,NOAC
            ,FRST_AUTH
            ,SCND_AUTH
            ,ZLM_DSCRPTN
        )           
        WITH NOAC_DETAIL AS
        (
            SELECT I_PROCID AS CASE_ID
                ,rownum AS SEQ
                ,substr(NOACitem, 1, instr(NOACitem, '%%', 1, 1)-1) NOAC
                ,substr(NOACitem, instr(NOACitem, '%%', 1, 1)+2 , instr(NOACitem, '%%', 1, 2) - instr(NOACitem, '%%', 1, 1) - 2) FRST_AUTH
                ,substr(NOACitem, instr(NOACitem, '%%', 1, 2)+2 , instr(NOACitem, '%%', 1, 3) - instr(NOACitem, '%%', 1, 2) - 2) SCND_AUTH
                ,substr(NOACitem, instr(NOACitem, '%%', 1, 3)+2) COMP_LEVEL
            FROM (
                SELECT 
                        regexp_substr(V_NATROFACTN_NOAC,'[^::]+', 1, level) AS NOACitem from dual
                         connect by regexp_substr(V_NATROFACTN_NOAC, '[^::]+', 1, level) is not null
                ) MYTBL
        )
        SELECT ND.CASE_ID, ND.SEQ, ND.NOAC, ND.FRST_AUTH, ND.SCND_AUTH, ND.COMP_LEVEL
          FROM NOAC_DETAIL ND
         WHERE ND.CASE_ID = I_PROCID;

    END IF;


-------- ATC_PERSONNEL_ACTION
    SELECT   FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_EFFECTIVE_DATE')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_NTE')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_VETS_PREF_CODE')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_INTER_WORKED')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_INTER_PROJECTED')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_INTER_WORKED_DAYSHOURS')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_INTER_PROJECTED_DAYSHOURS')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_LAST_APPT_DT_FROM')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_LAST_APPT_DT_TO')
      INTO 
            V_PACT_EFFCTV_DT
            ,V_PACT_NTE_DT
            ,V_PACT_VETS_PRFRNC
            ,V_PACT_INT_WRKD_LAST_APPT
            ,V_PACT_INT_WRKD_THIS_APPT
            ,V_PACT_INT_WRKD_LAST_APPT_TP
            ,V_PACT_INT_WRKD_THIS_APPT_TP
            ,V_PACT_DT_WRKD_LST_APPT_FROM
            ,V_PACT_DT_WRKD_LST_APPT_TO
       FROM DUAL;

    V_RECCNT := 0;
    SELECT COUNT(1)
      INTO V_RECCNT
      FROM HHS_CDC_HR.ATC_PERSONNEL_ACTION
     WHERE CASE_ID = I_PROCID;

    IF V_RECCNT = 0 THEN
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('INSERT INTO HHS_CDC_HR.ATC_PERSONNEL_ACTION');
        INSERT INTO HHS_CDC_HR.ATC_PERSONNEL_ACTION 
        (                        
            CASE_ID
            ,EFFCTV_DT
            ,NTE_DT
            ,VETS_PRFRNC
            ,INT_HRS_DYS_WRKD_LAST_APPT
            ,INT_HRS_DYS_WRKD_THIS_APPT
            ,INT_HRS_DYS_WRKD_LAST_APPT_TP
            ,INT_HRS_DYS_WRKD_THIS_APPT_TP
            ,DT_WRKD_LST_APPNTMNT_FROM
            ,DT_WRKD_LST_APPNTMNT_TO
        )
        VALUES 
        (
            I_PROCID
            ,V_PACT_EFFCTV_DT
            ,V_PACT_NTE_DT
            ,V_PACT_VETS_PRFRNC
            ,V_PACT_INT_WRKD_LAST_APPT
            ,V_PACT_INT_WRKD_THIS_APPT
            ,V_PACT_INT_WRKD_LAST_APPT_TP
            ,V_PACT_INT_WRKD_THIS_APPT_TP
            ,V_PACT_DT_WRKD_LST_APPT_FROM
            ,V_PACT_DT_WRKD_LST_APPT_TO
        );

    END;
    ELSE
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('UPDATE HHS_CDC_HR.ATC_PERSONNEL_ACTION');
        UPDATE HHS_CDC_HR.ATC_PERSONNEL_ACTION
           SET
            EFFCTV_DT = V_PACT_EFFCTV_DT
            ,NTE_DT = V_PACT_NTE_DT
            ,VETS_PRFRNC = V_PACT_VETS_PRFRNC
            ,INT_HRS_DYS_WRKD_LAST_APPT = V_PACT_INT_WRKD_LAST_APPT
            ,INT_HRS_DYS_WRKD_THIS_APPT = V_PACT_INT_WRKD_THIS_APPT
            ,INT_HRS_DYS_WRKD_LAST_APPT_TP = V_PACT_INT_WRKD_LAST_APPT_TP
            ,INT_HRS_DYS_WRKD_THIS_APPT_TP = V_PACT_INT_WRKD_THIS_APPT_TP
            ,DT_WRKD_LST_APPNTMNT_FROM = V_PACT_DT_WRKD_LST_APPT_FROM
            ,DT_WRKD_LST_APPNTMNT_TO = V_PACT_DT_WRKD_LST_APPT_TO
         WHERE CASE_ID = I_PROCID;

    END;
    END IF;

-------- ATC_COMPENSATION
    SELECT   FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'POS_CAN')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_FISCALYEAR')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_PRIOR_FEDERAL_SERVICE')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_HP_PAY_PLAN_CODE')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_HP_GRADE_ID')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_HP_STEP')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_HP_SALARY')
            --,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_LOCALITY')
            --,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_LOCALITY_REMARKS')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_TERMINATE_RET_ALLOWANCE')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_PAY_SET_AS_PAY_PLAN_CODE')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_PAY_SET_AS_GRADE_ID')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_PAY_SET_AS_STEP') --
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_PAY_SET_AS')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_INCENTIVES')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_MARKET_PAY')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_POST_DIFF_PERCENT')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_POST_DIFF_STATUS')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_COLA_PERCENT')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_COLA_STATUS')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_DANGER_PAY_STATUS')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_PAY_CORDINATED')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_PRIOR_YEAR')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_PRIOR_LOCATION')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_PRIOR_REMARKS')
      INTO 
            V_CMPNSTN_COMMON_ACCT_NO
            ,V_CMPNSTN_FED_FSCL_YR
            ,V_CMPNSTN_PRIOR_FED_SVC
            ,V_CMPNSTN_HIGHEST_PRE_PAY_PLAN
            ,V_CMPNSTN_HIGHEST_PRE_GRADE
            ,V_CMPNSTN_HIGHEST_PRE_STEP
            ,V_CMPNSTN_HIGHEST_PRE_SALARY
            --,V_CMPNSTN_LOCALITY
            --,V_CMPNSTN_REMARKS
            ,V_CMPNSTN_TERM_RTNTIN_ALLWNC
            ,V_CMPNSTN_PAY_SET_EQV_PAY_PLAN
            ,V_CMPNSTN_PAY_SET_EQV_GRADE
            ,V_CMPNSTN_PAY_SET_STEP
            ,V_CMPNSTN_PAY_SET_EQV_AMOUNT
            ,V_CMPNSTN_INCENTIVES
            ,V_CMPNSTN_MRKT_PAY
            ,V_CMPNSTN_POST_DIFF_PER
            ,V_CMPNSTN_POST_DIFF_STTS
            ,V_CMPNSTN_COLA_PER
            ,V_CMPNSTN_COLA_STTS
            ,V_CMPNSTN_DANGER_PAY_STTS
            ,V_CMPNSTN_PAY_CRDNTD_W_SO
            ,V_CMPNSTN_PRIOR_YR
            ,V_CMPNSTN_PRIOR_LCTN
            ,V_CMPNSTN_PRIOR_REMARKS
       FROM DUAL;

    V_RECCNT := 0;
    SELECT COUNT(1)
      INTO V_RECCNT
      FROM HHS_CDC_HR.ATC_COMPENSATION
     WHERE CASE_ID = I_PROCID;

    IF V_RECCNT = 0 THEN
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('INSERT INTO HHS_CDC_HR.ATC_COMPENSATION');
        INSERT INTO HHS_CDC_HR.ATC_COMPENSATION 
        (                        
            CASE_ID
            ,COMMON_ACCT_NO
            ,FED_FSCL_YR
            ,PRIOR_FED_SVC
            ,HIGHEST_PRE_PAY_PLAN
            ,HIGHEST_PRE_GRADE
            ,HIGHEST_PRE_STEP
            ,HIGHEST_PRE_SALARY
            --,LOCALITY
            --,REMARKS
            ,TERM_RTNTIN_ALLWNC
            ,PAY_SET_EQV_PAY_PLAN
            ,PAY_SET_EQV_GRADE
            ,PAY_SET_STEP
            ,PAY_SET_EQV_AMOUNT
            ,INCENTIVES
            ,MRKT_PAY
            ,POST_DIFF_PER
            ,POST_DIFF_STTS
            ,COLA_PER
            ,COLA_STTS
            ,DANGER_PAY_STTS
            ,PAY_CRDNTD_W_SO
            ,PRIOR_YR
            ,PRIOR_LCTN
            ,PRIOR_REMARKS       
        )
        VALUES 
        (
            I_PROCID
            ,V_CMPNSTN_COMMON_ACCT_NO
            ,V_CMPNSTN_FED_FSCL_YR
            ,V_CMPNSTN_PRIOR_FED_SVC
            ,V_CMPNSTN_HIGHEST_PRE_PAY_PLAN
            ,V_CMPNSTN_HIGHEST_PRE_GRADE
            ,V_CMPNSTN_HIGHEST_PRE_STEP
            ,V_CMPNSTN_HIGHEST_PRE_SALARY
            --,V_CMPNSTN_LOCALITY
            --,V_CMPNSTN_REMARKS
            ,V_CMPNSTN_TERM_RTNTIN_ALLWNC
            ,V_CMPNSTN_PAY_SET_EQV_PAY_PLAN
            ,V_CMPNSTN_PAY_SET_EQV_GRADE
            ,V_CMPNSTN_PAY_SET_STEP
            ,V_CMPNSTN_PAY_SET_EQV_AMOUNT
            ,V_CMPNSTN_INCENTIVES
            ,V_CMPNSTN_MRKT_PAY
            ,V_CMPNSTN_POST_DIFF_PER
            ,V_CMPNSTN_POST_DIFF_STTS
            ,V_CMPNSTN_COLA_PER
            ,V_CMPNSTN_COLA_STTS
            ,V_CMPNSTN_DANGER_PAY_STTS
            ,V_CMPNSTN_PAY_CRDNTD_W_SO
            ,V_CMPNSTN_PRIOR_YR
            ,V_CMPNSTN_PRIOR_LCTN
            ,V_CMPNSTN_PRIOR_REMARKS            
        );

    END;
    ELSE
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('UPDATE HHS_CDC_HR.ATC_COMPENSATION');
        UPDATE HHS_CDC_HR.ATC_COMPENSATION
           SET
            COMMON_ACCT_NO = V_CMPNSTN_COMMON_ACCT_NO
            ,FED_FSCL_YR = V_CMPNSTN_FED_FSCL_YR
            ,PRIOR_FED_SVC = V_CMPNSTN_PRIOR_FED_SVC
            ,HIGHEST_PRE_PAY_PLAN = V_CMPNSTN_HIGHEST_PRE_PAY_PLAN
            ,HIGHEST_PRE_GRADE = V_CMPNSTN_HIGHEST_PRE_GRADE
            ,HIGHEST_PRE_STEP = V_CMPNSTN_HIGHEST_PRE_STEP
            ,HIGHEST_PRE_SALARY = V_CMPNSTN_HIGHEST_PRE_SALARY
            --,LOCALITY = V_CMPNSTN_LOCALITY
            --,REMARKS = V_CMPNSTN_REMARKS
            ,TERM_RTNTIN_ALLWNC = V_CMPNSTN_TERM_RTNTIN_ALLWNC
            ,PAY_SET_EQV_PAY_PLAN = V_CMPNSTN_PAY_SET_EQV_PAY_PLAN
            ,PAY_SET_EQV_GRADE = V_CMPNSTN_PAY_SET_EQV_GRADE
            ,PAY_SET_STEP = V_CMPNSTN_PAY_SET_STEP
            ,PAY_SET_EQV_AMOUNT = V_CMPNSTN_PAY_SET_EQV_AMOUNT
            ,INCENTIVES = V_CMPNSTN_INCENTIVES
            ,MRKT_PAY = V_CMPNSTN_MRKT_PAY
            ,POST_DIFF_PER = V_CMPNSTN_POST_DIFF_PER
            ,POST_DIFF_STTS = V_CMPNSTN_POST_DIFF_STTS
            ,COLA_PER = V_CMPNSTN_COLA_PER
            ,COLA_STTS = V_CMPNSTN_COLA_STTS
            ,DANGER_PAY_STTS = V_CMPNSTN_DANGER_PAY_STTS
            ,PAY_CRDNTD_W_SO = V_CMPNSTN_PAY_CRDNTD_W_SO
            ,PRIOR_YR = V_CMPNSTN_PRIOR_YR
            ,PRIOR_LCTN = V_CMPNSTN_PRIOR_LCTN
            ,PRIOR_REMARKS = V_CMPNSTN_PRIOR_REMARKS
         WHERE CASE_ID = I_PROCID;

    END;
    END IF;

-------- ATC_BENEFITS
    SELECT   FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_VISA_TYPE')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_ENTITLED_TO_BENEFITS')
      INTO 
            V_BNFTS_VISA_TP
            ,V_BNFTS_EMP_ENTTLD_TO_BNFTS
       FROM DUAL;

    V_RECCNT := 0;
    SELECT COUNT(1)
      INTO V_RECCNT
      FROM HHS_CDC_HR.ATC_BENEFITS
     WHERE CASE_ID = I_PROCID;

    IF V_RECCNT = 0 THEN
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('INSERT INTO HHS_CDC_HR.ATC_BENEFITS');
        INSERT INTO HHS_CDC_HR.ATC_BENEFITS 
        (                        
            CASE_ID
            ,VISA_TP
            ,EMP_ENTTLD_TO_BNFTS
        )
        VALUES 
        (
            I_PROCID
            ,V_BNFTS_VISA_TP
            ,V_BNFTS_EMP_ENTTLD_TO_BNFTS
        );

    END;
    ELSE
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('UPDATE HHS_CDC_HR.ATC_BENEFITS');
        UPDATE HHS_CDC_HR.ATC_BENEFITS
           SET
            VISA_TP = V_BNFTS_VISA_TP
            ,EMP_ENTTLD_TO_BNFTS = V_BNFTS_EMP_ENTTLD_TO_BNFTS
         WHERE CASE_ID = I_PROCID;

    END;
    END IF;

-------- ATC_SELECTED_BENEFITS
    DELETE 
      FROM HHS_CDC_HR.ATC_SELECTED_BENEFITS
     WHERE CASE_ID = I_PROCID;

    SELECT FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_ENTITLED_BENEFITS')
      INTO V_BNFTS_ENTTLD_BNFTS
      FROM DUAL;

    IF V_BNFTS_ENTTLD_BNFTS IS NOT NULL THEN
        --DBMS_OUTPUT.PUT_LINE('V_BNFTS_ENTTLD_BNFTS=' || V_BNFTS_ENTTLD_BNFTS);
        INSERT INTO HHS_CDC_HR.ATC_SELECTED_BENEFITS 
        (
            CASE_ID
            ,SEQ
            ,ENTTLD_BNFT
        )        
        SELECT I_PROCID
               ,ROWNUM
               ,regexp_substr(V_BNFTS_ENTTLD_BNFTS,'[^::]+', 1, level) from dual
                     connect by regexp_substr(V_BNFTS_ENTTLD_BNFTS, '[^::]+', 1, level) is not null;

    END IF;  

-------- APP_TRACKING
    SELECT   FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'RETROACTIVE')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'RETRO_MEMO_DATE')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ETHICS_CLEARANCE_STATUS')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ETHICS_DECISION_DATE')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'SECURITY_CLEARANCE_STATUS')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'SECURITY_DECISION_DATE')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'WORK_AUTHORIZATION_STATUS')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'WORK_AUTHORIZATION_DECISION_DATE')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'CAP_HR_POS_NUM')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'JOB_CODE')
      INTO 
            V_TRCK_CSO_DEPUTY_DIR_APPRVL
            ,V_TRCK_MEMO_SGND_DT
            ,V_TRCK_ETHICS_CLRNC_STTS
            ,V_TRCK_ETHICS_DCSN_RCVD_DT
            ,V_TRCK_SEC_CLRNC_STTS
            ,V_TRCK_SEC_DCSN_RCVD_DT
            ,V_TRCK_WRK_ATH_STTS
            ,V_TRCK_WRK_ATH_DCSN_RCVD_DT
            ,V_TRCK_CAPHR_POS_NO
            ,V_TRCK_JOB_CD
       FROM DUAL;

    V_RECCNT := 0;
    SELECT COUNT(1)
      INTO V_RECCNT
      FROM HHS_CDC_HR.APP_TRACKING
     WHERE CASE_ID = I_PROCID;

    IF V_RECCNT = 0 THEN
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('INSERT INTO HHS_CDC_HR.APP_TRACKING');
        INSERT INTO HHS_CDC_HR.APP_TRACKING 
        (                        
            CASE_ID
            ,CSO_DEPUTY_DIR_APPRVL
            ,MEMO_SGND_DT
            ,ETHICS_CLRNC_STTS
            ,ETHICS_DCSN_RCVD_DT
            ,SEC_CLRNC_STTS
            ,SEC_DCSN_RCVD_DT
            ,WRK_ATHRZTN_STTS
            ,WRK_ATHRZTN_DCSN_RCVD_DT
            ,CAPHR_POS_NO
            ,JOB_CD
        )
        VALUES 
        (
            I_PROCID
            ,V_TRCK_CSO_DEPUTY_DIR_APPRVL
            ,V_TRCK_MEMO_SGND_DT
            ,V_TRCK_ETHICS_CLRNC_STTS
            ,V_TRCK_ETHICS_DCSN_RCVD_DT
            ,V_TRCK_SEC_CLRNC_STTS
            ,V_TRCK_SEC_DCSN_RCVD_DT
            ,V_TRCK_WRK_ATH_STTS
            ,V_TRCK_WRK_ATH_DCSN_RCVD_DT
            ,V_TRCK_CAPHR_POS_NO
            ,V_TRCK_JOB_CD
        );

    END;
    ELSE
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('UPDATE HHS_CDC_HR.APP_TRACKING');
        UPDATE HHS_CDC_HR.APP_TRACKING
           SET
            CSO_DEPUTY_DIR_APPRVL = V_TRCK_CSO_DEPUTY_DIR_APPRVL
            ,MEMO_SGND_DT = V_TRCK_MEMO_SGND_DT
            ,ETHICS_CLRNC_STTS = V_TRCK_ETHICS_CLRNC_STTS
            ,ETHICS_DCSN_RCVD_DT = V_TRCK_ETHICS_DCSN_RCVD_DT
            ,SEC_CLRNC_STTS = V_TRCK_SEC_CLRNC_STTS
            ,SEC_DCSN_RCVD_DT = V_TRCK_SEC_DCSN_RCVD_DT
            ,WRK_ATHRZTN_STTS = V_TRCK_WRK_ATH_STTS
            ,WRK_ATHRZTN_DCSN_RCVD_DT = V_TRCK_WRK_ATH_DCSN_RCVD_DT
            ,CAPHR_POS_NO = V_TRCK_CAPHR_POS_NO
            ,JOB_CD = V_TRCK_JOB_CD
         WHERE CASE_ID = I_PROCID;

    END;
    END IF;

-------- APP_APPROVAL
    SELECT   FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'HR_PROCESSOR_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'HR_PROCESSOR_DATE')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'HR_STAFFING_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'HR_STAFFING_DATE')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_SIGN_OFF_REQ_2')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_APPROVER_2')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'ATC_APPROVER_EMAIL_2')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'HR_SENIOR_STAFFING_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'HR_SENIOR_STAFFING_DATE')
      INTO 
            V_APVL_HR_ASSSTNT_NM
            ,V_APVL_HR_ASSSTNT_APPRVL_DT
            ,V_APVL_HRS_SPC_NM
            ,V_APVL_HRS_SPC_APPRVL_DT
            ,V_APVL_ADDTNL_APPRVL_RQRD
            ,V_APVL_ADDTNL_APPRVL_NM
            ,V_APVL_ADDTNL_APPRVL_EMAIL
            ,V_APVL_SR_HRS_SPC_NM
            ,V_APVL_SR_HRS_SPC_APPRVL_DT
       FROM DUAL;

    V_RECCNT := 0;
    SELECT COUNT(1)
      INTO V_RECCNT
      FROM HHS_CDC_HR.APP_APPROVAL
     WHERE CASE_ID = I_PROCID;

    IF V_RECCNT = 0 THEN
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('INSERT INTO HHS_CDC_HR.APP_APPROVAL');
        INSERT INTO HHS_CDC_HR.APP_APPROVAL 
        (                        
            CASE_ID
            ,HR_ASSSTNT_NM
            ,HR_ASSSTNT_APPRVL_DT
            ,HRS_SPC_NM
            ,HRS_SPC_APPRVL_DT
            ,ADDTNL_APPRVL_RQRD
            ,ADDTNL_APPRVL_NM
            ,ADDTNL_APPRVL_EMAIL
            ,SR_HRS_SPC_NM
            ,SR_HRS_SPC_APPRVL_DT
        )
        VALUES 
        (
            I_PROCID
            ,V_APVL_HR_ASSSTNT_NM
            ,V_APVL_HR_ASSSTNT_APPRVL_DT
            ,V_APVL_HRS_SPC_NM
            ,V_APVL_HRS_SPC_APPRVL_DT
            ,V_APVL_ADDTNL_APPRVL_RQRD
            ,V_APVL_ADDTNL_APPRVL_NM
            ,V_APVL_ADDTNL_APPRVL_EMAIL
            ,V_APVL_SR_HRS_SPC_NM
            ,V_APVL_SR_HRS_SPC_APPRVL_DT
        );

    END;
    ELSE
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('UPDATE HHS_CDC_HR.APP_APPROVAL');
        UPDATE HHS_CDC_HR.APP_APPROVAL
           SET
            HR_ASSSTNT_NM = V_APVL_HR_ASSSTNT_NM
            ,HR_ASSSTNT_APPRVL_DT = V_APVL_HR_ASSSTNT_APPRVL_DT
            ,HRS_SPC_NM = V_APVL_HRS_SPC_NM
            ,HRS_SPC_APPRVL_DT = V_APVL_HRS_SPC_APPRVL_DT
            ,ADDTNL_APPRVL_RQRD = V_APVL_ADDTNL_APPRVL_RQRD
            ,ADDTNL_APPRVL_NM = V_APVL_ADDTNL_APPRVL_NM
            ,ADDTNL_APPRVL_EMAIL = V_APVL_ADDTNL_APPRVL_EMAIL
            ,SR_HRS_SPC_NM = V_APVL_SR_HRS_SPC_NM
            ,SR_HRS_SPC_APPRVL_DT = V_APVL_SR_HRS_SPC_APPRVL_DT
         WHERE CASE_ID = I_PROCID;

    END;
    END IF;    

-------- POSITION_BUILD_APPROVAL
    SELECT   FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'POSITION_BUILD_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'OF8_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'CAPHR_POS_NUM_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'JOB_CODE_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'PM_BUS_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'PM_SUP_STAT_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'PM_FLSA_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'PM_ADMIN_CODE_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'PM_STEWARD_NAME_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'PM_STEWARD_DATE_APPROVAL')
      INTO 
            V_POSBLD_ACTV_N_ACCRT
            ,V_POSBLD_ALL_SIGN_OF8
            ,V_POSBLD_CAPHR_POS_NO
            ,V_POSBLD_JOB_CODE
            ,V_POSBLD_BUS_ARRVD
            ,V_POSBLD_SPRVSRY_STTS_APPRVD
            ,V_POSBLD_FLSA_APPRVD
            ,V_POSBLD_ADMIN_CD_APPRVD
            ,V_POSBLD_PM_STWRD_NM
            ,V_POSBLD_PM_STWRD_APPRVD
       FROM DUAL;

    V_RECCNT := 0;
    SELECT COUNT(1)
      INTO V_RECCNT
      FROM HHS_CDC_HR.POSITION_BUILD_APPROVAL
     WHERE CASE_ID = I_PROCID;

    IF V_RECCNT = 0 THEN
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('INSERT INTO HHS_CDC_HR.POSITION_BUILD_APPROVAL');
        INSERT INTO HHS_CDC_HR.POSITION_BUILD_APPROVAL 
        (                        
            CASE_ID
            ,ACTV_N_ACCRT
            ,ALL_SIGN_OF8
            ,CAPHR_POS_NO
            ,JOB_CODE
            ,BUS_ARRVD
            ,SPRVSRY_STTS_APPRVD
            ,FLSA_APPRVD
            ,ADMIN_CD_APPRVD
            ,PM_STWRD_NM
            ,PM_STWRD_APPRVD
        )
        VALUES 
        (
            I_PROCID
            ,V_POSBLD_ACTV_N_ACCRT
            ,V_POSBLD_ALL_SIGN_OF8
            ,V_POSBLD_CAPHR_POS_NO
            ,V_POSBLD_JOB_CODE
            ,V_POSBLD_BUS_ARRVD
            ,V_POSBLD_SPRVSRY_STTS_APPRVD
            ,V_POSBLD_FLSA_APPRVD
            ,V_POSBLD_ADMIN_CD_APPRVD
            ,V_POSBLD_PM_STWRD_NM
            ,V_POSBLD_PM_STWRD_APPRVD
        );

    END;
    ELSE
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('UPDATE HHS_CDC_HR.POSITION_BUILD_APPROVAL');
        UPDATE HHS_CDC_HR.POSITION_BUILD_APPROVAL
           SET
            ACTV_N_ACCRT = V_POSBLD_ACTV_N_ACCRT
            ,ALL_SIGN_OF8 = V_POSBLD_ALL_SIGN_OF8
            ,CAPHR_POS_NO = V_POSBLD_CAPHR_POS_NO
            ,JOB_CODE = V_POSBLD_JOB_CODE
            ,BUS_ARRVD = V_POSBLD_BUS_ARRVD
            ,SPRVSRY_STTS_APPRVD = V_POSBLD_SPRVSRY_STTS_APPRVD
            ,FLSA_APPRVD = V_POSBLD_FLSA_APPRVD
            ,ADMIN_CD_APPRVD = V_POSBLD_ADMIN_CD_APPRVD
            ,PM_STWRD_NM = V_POSBLD_PM_STWRD_NM
            ,PM_STWRD_APPRVD = V_POSBLD_PM_STWRD_APPRVD
         WHERE CASE_ID = I_PROCID;

    END;
    END IF;  


-------- TSA_PROCESSING
    SELECT   FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'PROCESSOR_NAME_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'PROCESSOR_DATE_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'LEAD_PROCESSOR_NEEDED')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'LEAD_PROCESSOR')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'LEAD_PROCESSOR_EMAIL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'LEAD_PROCESSOR_NAME_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'LEAD_PROCESSOR_DATE_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'EOPF_APPROVAL')
            ,FN_GET_XML_FIELD_VALUE(V_FD_FIELD_DATA, 'QUALITY_APPROVAL')
      INTO 
            V_TSAPRC_TSA_PRCSSR_NM
            ,V_TSAPRC_TSA_PRCSSR_APPRVL_DT
            ,V_TSAPRC_ADDL_APPRVL_RQRD
            ,V_TSAPRC_ADDL_TSA_NM
            ,V_TSAPRC_ADDL_TSA_EMAIL
            ,V_TSAPRC_LD_TSA_NM
            ,V_TSAPRC_LD_TSA_APPRVL_DT
            ,V_TSAPRC_DOC_SCANNED_TO_EOPF
            ,V_TSAPRC_QLTY_ASSRNC_RVW_CMPL
       FROM DUAL; 

    V_RECCNT := 0;
    SELECT COUNT(1)
      INTO V_RECCNT
      FROM HHS_CDC_HR.TSA_PROCESSING
     WHERE CASE_ID = I_PROCID;

    IF V_RECCNT = 0 THEN
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('INSERT INTO HHS_CDC_HR.TSA_PROCESSING');
        INSERT INTO HHS_CDC_HR.TSA_PROCESSING 
        (                        
            CASE_ID
            ,TSA_PRCSSR_NM
            ,TSA_PRCSSR_APPRVL_DT
            ,ADDTNL_APPRVL_RQRD
            ,ADDTNL_TSA_PRCSSR_NM
            ,ADDTNL_TSA_PRCSSR_EMAIL
            ,LEAD_TSA_PRCSSR_NM
            ,LEAD_TSA_PRCSSR_APPRVL_DT
            ,DOC_SCANNED_TO_EOPF
            ,QLTY_ASSRNC_RVW_CMPL
        )
        VALUES 
        (
            I_PROCID
            ,V_TSAPRC_TSA_PRCSSR_NM
            ,V_TSAPRC_TSA_PRCSSR_APPRVL_DT
            ,V_TSAPRC_ADDL_APPRVL_RQRD
            ,V_TSAPRC_ADDL_TSA_NM
            ,V_TSAPRC_ADDL_TSA_EMAIL
            ,V_TSAPRC_LD_TSA_NM
            ,V_TSAPRC_LD_TSA_APPRVL_DT
            ,V_TSAPRC_DOC_SCANNED_TO_EOPF
            ,V_TSAPRC_QLTY_ASSRNC_RVW_CMPL
        );

    END;
    ELSE
    BEGIN
        --DBMS_OUTPUT.PUT_LINE('UPDATE HHS_CDC_HR.TSA_PROCESSING');
        UPDATE HHS_CDC_HR.TSA_PROCESSING
           SET
            TSA_PRCSSR_NM = V_TSAPRC_TSA_PRCSSR_NM
            ,TSA_PRCSSR_APPRVL_DT = V_TSAPRC_TSA_PRCSSR_APPRVL_DT
            ,ADDTNL_APPRVL_RQRD = V_TSAPRC_ADDL_APPRVL_RQRD
            ,ADDTNL_TSA_PRCSSR_NM = V_TSAPRC_ADDL_TSA_NM
            ,ADDTNL_TSA_PRCSSR_EMAIL = V_TSAPRC_ADDL_TSA_EMAIL
            ,LEAD_TSA_PRCSSR_NM = V_TSAPRC_LD_TSA_NM
            ,LEAD_TSA_PRCSSR_APPRVL_DT = V_TSAPRC_LD_TSA_APPRVL_DT
            ,DOC_SCANNED_TO_EOPF = V_TSAPRC_DOC_SCANNED_TO_EOPF
            ,QLTY_ASSRNC_RVW_CMPL = V_TSAPRC_QLTY_ASSRNC_RVW_CMPL
         WHERE CASE_ID = I_PROCID; 

    END;
    END IF;      

END SP_UPDATE_NAMEDACTION_TBLS;