
DELETE FROM HHS_CDC_HR.TBL_LOOKUP
WHERE TBL_LTYPE IN ('Title5_ParActionType', 'NonTitle5_ParActionType');

INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13900,'Title5_ParActionType','Promotion','Promotion',1,1);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13901,'Title5_ParActionType','Promotion NTE','Promotion NTE',1,2);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13902,'Title5_ParActionType','Change To Lower Grade','Change To Lower Grade',1,3);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13903,'Title5_ParActionType','Extension','Extension',1,4);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13904,'Title5_ParActionType','Reassignment','Reassignment',1,5);

INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13950,'NonTitle5_ParActionType','Conversion','Conversion',1,1);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13951,'NonTitle5_ParActionType','Conversion NTE','Conversion NTE',1,2);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13952,'NonTitle5_ParActionType','Stipend Increase','Stipend Increase',1,3);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13953,'NonTitle5_ParActionType','Extension','Extension',1,4);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13954,'NonTitle5_ParActionType','Reassignment','Reassignment',1,5);

COMMIT;
/

--DROP TABLE HHS_CDC_HR.ERA_LOG_CAPHR_JR;

CREATE TABLE HHS_CDC_HR.ERA_LOG_CAPHR_JR
(
    ID                          INTEGER NOT NULL
    ,JOB_OPENING_ID             VARCHAR2(200)
    ,PROCID                     INTEGER
    ,ERA_STATUS                 VARCHAR2(100)
    ,DSCRPTN                    VARCHAR2(4000)
    ,CREATIONDTIME              TIMESTAMP
);


ALTER TABLE HHS_CDC_HR.ERA_LOG_CAPHR_JR ADD CONSTRAINT ERA_LOG_CAPHR_JR_PK PRIMARY KEY (ID);
/

CREATE INDEX HHS_CDC_HR.ERA_LOG_CAPHR_JR_NK1 ON HHS_CDC_HR.ERA_LOG_CAPHR_JR (JOB_OPENING_ID);
/

CREATE INDEX HHS_CDC_HR.ERA_LOG_CAPHR_JR_NK2 ON HHS_CDC_HR.ERA_LOG_CAPHR_JR (PROCID);
/

CREATE SEQUENCE HHS_CDC_HR.ERA_LOG_CAPHR_JR_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
/

CREATE OR REPLACE TRIGGER HHS_CDC_HR.ERA_LOG_CAPHR_JR_BIR
BEFORE INSERT ON HHS_CDC_HR.ERA_LOG_CAPHR_JR
FOR EACH ROW
BEGIN
	SELECT ERA_LOG_CAPHR_JR_SEQ.NEXTVAL
	INTO :NEW.ID
	FROM DUAL;
END;
/

--DROP TABLE HHS_CDC_HR.ERA_LOG_CAPHR_LAST_RUN;
CREATE TABLE HHS_CDC_HR.ERA_LOG_CAPHR_LAST_RUN
(
    ERA_SVC_TYPE   VARCHAR2(100)
    ,LAST_RUN_DTIME  TIMESTAMP
);
/
ALTER TABLE HHS_CDC_HR.ERA_LOG_CAPHR_LAST_RUN ADD CONSTRAINT ERA_LOG_CAPHR_LAST_RUN_PK PRIMARY KEY (ERA_SVC_TYPE);
/

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ERA_LOG_CAPHR_JR TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ERA_LOG_CAPHR_JR TO HHS_CDC_HR_DEV_ROLE;
/
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ERA_LOG_CAPHR_LAST_RUN TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ERA_LOG_CAPHR_LAST_RUN TO HHS_CDC_HR_DEV_ROLE;
/

GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_NAMEDACTION_TBLS TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_NAMEDACTION_TBLS TO HHS_CDC_HR_DEV_ROLE;
/

-- LOGIN AS HHS_HR (Let Christina include GRANT in her deployment script)
GRANT SELECT ON HHS_HR.VW_EHRP_15_MIN TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT ON HHS_HR.VW_EHRP_15_MIN TO HHS_CDC_HR_DEV_ROLE;
/



-- LOGIN AS BizFlow
DELETE FROM HHS_CDC_HR.ERA_LOG_CAPHR_LAST_RUN;
INSERT INTO HHS_CDC_HR.ERA_LOG_CAPHR_LAST_RUN(ERA_SVC_TYPE) VALUES ('CAPHR-ERA-JR');
INSERT INTO HHS_CDC_HR.ERA_LOG_CAPHR_LAST_RUN(ERA_SVC_TYPE) VALUES ('CAPHR-ERA-PAR');
COMMIT;
/


















