------------------------------------------------------------------------------------------
--  Name	            : 	6_grant_cdc_hr.sql
--	Author				:	Taeho Lee <thee@bizflow.com>
--	Copyright			:	BizFlow Corp.	
--	
--	Project				:	HHS CDC HR Workflow Solution - EWITS 2.0
--	Purpose				:	Grant tables access to CDC database roles
--	
--  Example
--  To use in SQL statements:
--
-- 	WHEN		WHO			WHAT		
-- 	-----------	--------	-------------------------------------------------------
-- 	04/13/2018	THLEE		Created
------------------------------------------------------------------------------------------

-- Tables
GRANT SELECT ON HHS_CDC_HR.AUTHORIZED_INCENTIVE TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.AUTHORIZED_INCENTIVE TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.CLA_CONDITION TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.CLA_CONDITION TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.CLA_STANDARD TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.CLA_STANDARD TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.CLASSIFICATION TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.CLASSIFICATION TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.CLASSIFIED_POS_TITLE TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.CLASSIFIED_POS_TITLE TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.CONCURRENCE TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.CONCURRENCE TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.CONSIDERATION_AREA TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.CONSIDERATION_AREA TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.DUTY_STATION TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.DUTY_STATION TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.EMP_CONDITION TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.EMP_CONDITION TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.FINANCIAL_STATEMENT TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.FINANCIAL_STATEMENT TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.GRADE TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.GRADE TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.HR_CASE TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.HR_CASE TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.LANGUAGE TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.LANGUAGE TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.POS_TITLE_SERIES TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.POS_TITLE_SERIES TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.POSITION TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.POSITION TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.REC_SME TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.REC_SME TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.RECRUITMENT TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.RECRUITMENT TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT ON HHS_CDC_HR.VALIDATION TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT ON HHS_CDC_HR.VALIDATION TO HHS_CDC_HR_RW_ROLE;

-- Base Tables
GRANT SELECT ON HHS_CDC_HR.TBL_FORM_DTL TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT ON HHS_CDC_HR.TBL_FORM_DTL TO HHS_CDC_HR_DEV_ROLE;

GRANT SELECT ON HHS_CDC_HR.TBL_FORM_DTL_AUDIT TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT ON HHS_CDC_HR.TBL_FORM_DTL_AUDIT TO HHS_CDC_HR_DEV_ROLE;

GRANT SELECT ON HHS_CDC_HR.TBL_LOOKUP TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT ON HHS_CDC_HR.TBL_LOOKUP TO HHS_CDC_HR_DEV_ROLE;

GRANT SELECT ON HHS_CDC_HR.VALIDATION TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT ON HHS_CDC_HR.VALIDATION TO HHS_CDC_HR_DEV_ROLE;

-- Views
GRANT SELECT ON HHS_CDC_HR.ADMIN_CODES TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT ON HHS_CDC_HR.ADMIN_CODES TO HHS_CDC_HR_DEV_ROLE;

--GRANT SELECT ON HHS_CDC_HR.V_TBL_LOOKUP TO HHS_CDC_HR_RW_ROLE;
--GRANT SELECT ON HHS_CDC_HR.V_TBL_LOOKUP TO HHS_CDC_HR_DEV_ROLE;

--Grant Business Tables in HHS_CDC_HR
--GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CDC_HR.APPROVALS TO HHS_CDC_HR_DEV_ROLE;
--GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CDC_HR.APPROVALS TO HHS_CDC_HR_RW_ROLE;

--Grant Stored Procedure or Function or Sequence
GRANT EXECUTE ON HHS_CDC_HR.FN_CONCAT_HR_RECORDS TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_CONCAT_HR_RECORDS TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.FN_GET_FORM_DATA_FIELD_VALUE TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_GET_FORM_DATA_FIELD_VALUE TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.FN_GET_XML_FIELD_VALUE TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_GET_XML_FIELD_VALUE TO HHS_CDC_HR_DEV_ROLE;


