
CREATE TABLE HHS_CDC_HR.APP_APPROVAL
(
	CASE_ID              NUMBER(10) NOT NULL ,
	HR_ASSSTNT_NM        VARCHAR2(200) NULL ,
	HR_ASSSTNT_APPRVL_DT VARCHAR2(20) NULL ,
	HRS_SPC_NM           VARCHAR2(200) NULL ,
	HRS_SPC_APPRVL_DT    VARCHAR2(20) NULL ,
	ADDTNL_APPRVL_RQRD   VARCHAR(20) NULL ,
	ADDTNL_APPRVL_NM     VARCHAR2(200) NULL ,
	ADDTNL_APPRVL_EMAIL  VARCHAR2(100) NULL ,
	SR_HRS_SPC_NM        VARCHAR2(200) NULL ,
	SR_HRS_SPC_APPRVL_DT VARCHAR2(20) NULL 
);



CREATE UNIQUE INDEX XPKAppointment_Approval ON HHS_CDC_HR.APP_APPROVAL
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.APP_APPROVAL
	ADD CONSTRAINT  XPKAppointment_Approval PRIMARY KEY (CASE_ID);



CREATE TABLE HHS_CDC_HR.APP_TRACKING
(
	CASE_ID              NUMBER(10) NOT NULL ,
	CSO_DEPUTY_DIR_APPRVL VARCHAR2(400) NULL ,
	MEMO_SGND_DT         VARCHAR2(20) NULL ,
	CAPHR_POS_NO         VARCHAR2(100) NULL ,
	JOB_CD               VARCHAR2(100) NULL ,
	ETHICS_CLRNC_STTS    VARCHAR2(100) NULL ,
	ETHICS_DCSN_RCVD_DT  VARCHAR2(20) NULL ,
	SEC_CLRNC_STTS       VARCHAR2(100) NULL ,
	SEC_DCSN_RCVD_DT     VARCHAR2(20) NULL ,
	WRK_ATHRZTN_STTS     VARCHAR2(20) NULL ,
	WRK_ATHRZTN_DCSN_RCVD_DT VARCHAR2(20) NULL 
);



CREATE UNIQUE INDEX XPKAppointment_Tracking ON HHS_CDC_HR.APP_TRACKING
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.APP_TRACKING
	ADD CONSTRAINT  XPKAppointment_Tracking PRIMARY KEY (CASE_ID);



CREATE TABLE HHS_CDC_HR.APPOINTMENT
(
	CASE_ID              NUMBER(10) NOT NULL ,
	RQST_TP              VARCHAR2(100) NULL ,
	HIRING_METHOD        VARCHAR2(20) NULL ,
	ADMIN_CD             VARCHAR2(20) NULL ,
	ORG_NM               VARCHAR2(200) NULL ,
	SHRD_CERT            VARCHAR2(200) NULL ,
	VA_NO                VARCHAR2(200) NULL ,
	CERT_NO              VARCHAR2(200) NULL ,
	AREA_OF_CONSIDERATION VARCHAR(200) NULL ,
	NON_COMP_TYPE        VARCHAR2(200) NULL ,
	JOB_REQ_NO           VARCHAR2(100) NULL ,
	POS_BSD_MGMT_SYS_NO  VARCHAR2(100) NULL ,
	SO_NM                VARCHAR2(100) NULL ,
	SO_EMAIL             VARCHAR2(100) NULL ,
	CIO_ADMN_NM          VARCHAR2(100) NULL ,
	CIO_ADMN_EMAIL       VARCHAR2(100) NULL ,
	HRO_SPC_NM           VARCHAR2(100) NULL ,
	HRO_SPC_EMAIL        VARCHAR2(100) NULL ,
	CLA_SPC_NM           VARCHAR2(100) NULL ,
	CLA_SPC_EMAIL        VARCHAR2(100) NULL ,
	HRO_SPC_ASSSTNT_NM   VARCHAR2(100) NULL ,
	HRO_SPC_ASSSTNT_EMAIL VARCHAR2(100) NULL 
);



CREATE UNIQUE INDEX XPKAppointment ON HHS_CDC_HR.APPOINTMENT
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.APPOINTMENT
	ADD CONSTRAINT  XPKAppointment PRIMARY KEY (CASE_ID);



CREATE TABLE HHS_CDC_HR.ATC_BENEFITS
(
	CASE_ID              NUMBER(10) NOT NULL ,
	VISA_TP              VARCHAR2(400) NULL ,
	EMP_ENTTLD_TO_BNFTS  VARCHAR2(100) NULL 
);



CREATE UNIQUE INDEX XPKATC_Benefits ON HHS_CDC_HR.ATC_BENEFITS
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.ATC_BENEFITS
	ADD CONSTRAINT  XPKATC_Benefits PRIMARY KEY (CASE_ID);



CREATE TABLE HHS_CDC_HR.ATC_COMPENSATION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	COMMON_ACCT_NO       VARCHAR2(400) NULL ,
	FED_FSCL_YR          VARCHAR2(100) NULL ,
	PRIOR_FED_SVC        VARCHAR2(400) NULL ,
	HIGHEST_PRE_PAY_PLAN VARCHAR2(400) NULL ,
	HIGHEST_PRE_GRADE    VARCHAR2(400) NULL ,
	HIGHEST_PRE_STEP     VARCHAR2(400) NULL ,
	HIGHEST_PRE_SALARY   VARCHAR2(400) NULL ,
	PRIOR_REMARKS        VARCHAR2(4000) NULL ,
	PRIOR_LCTN           VARCHAR2(400) NULL ,
	PRIOR_YR             VARCHAR2(20) NULL ,
	TERM_RTNTIN_ALLWNC   VARCHAR2(400) NULL ,
	PAY_SET_EQV_PAY_PLAN VARCHAR2(400) NULL ,
	PAY_SET_EQV_GRADE    VARCHAR2(400) NULL ,
	PAY_SET_STEP         VARCHAR2(400) NULL ,
	PAY_SET_EQV_AMOUNT   VARCHAR2(400) NULL ,
	INCENTIVES           VARCHAR2(400) NULL ,
	MRKT_PAY             VARCHAR2(400) NULL ,
	POST_DIFF_PER        VARCHAR2(400) NULL ,
	POST_DIFF_STTS       VARCHAR2(100) NULL ,
	COLA_PER             VARCHAR2(400) NULL ,
	COLA_STTS            VARCHAR2(100) NULL ,
	DANGER_PAY_STTS      VARCHAR2(100) NULL ,
	PAY_CRDNTD_W_SO      VARCHAR2(400) NULL 
);



CREATE UNIQUE INDEX XPKATC_Compensation ON HHS_CDC_HR.ATC_COMPENSATION
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.ATC_COMPENSATION
	ADD CONSTRAINT  XPKATC_Compensation PRIMARY KEY (CASE_ID);



CREATE TABLE HHS_CDC_HR.ATC_NATURE_OF_ACTION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	NOAC                 VARCHAR2(400) NULL ,
	FRST_AUTH            VARCHAR2(400) NULL ,
	SCND_AUTH            VARCHAR2(400) NULL ,
	ZLM_DSCRPTN          VARCHAR2(4000) NULL 
);



CREATE UNIQUE INDEX XPKATC_Nature_of_Action ON HHS_CDC_HR.ATC_NATURE_OF_ACTION
(CASE_ID   ASC,SEQ   ASC);



ALTER TABLE HHS_CDC_HR.ATC_NATURE_OF_ACTION
	ADD CONSTRAINT  XPKATC_Nature_of_Action PRIMARY KEY (CASE_ID,SEQ);



CREATE TABLE HHS_CDC_HR.ATC_PERSONNEL_ACTION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	EFFCTV_DT            VARCHAR2(20) NULL ,
	NTE_DT               VARCHAR2(20) NULL ,
	VETS_PRFRNC          VARCHAR2(400) NULL ,
	INT_HRS_DYS_WRKD_LAST_APPT VARCHAR2(100) NULL ,
	INT_HRS_DYS_WRKD_THIS_APPT VARCHAR2(100) NULL ,
	INT_HRS_DYS_WRKD_LAST_APPT_TP VARCHAR2(10) NULL ,
	INT_HRS_DYS_WRKD_THIS_APPT_TP VARCHAR2(10) NULL ,
	DT_WRKD_LST_APPNTMNT_FROM VARCHAR2(20) NULL ,
	DT_WRKD_LST_APPNTMNT_TO VARCHAR2(20) NULL 
);



CREATE UNIQUE INDEX XPKATC_Personnel_Action ON HHS_CDC_HR.ATC_PERSONNEL_ACTION
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.ATC_PERSONNEL_ACTION
	ADD CONSTRAINT  XPKATC_Personnel_Action PRIMARY KEY (CASE_ID);



CREATE TABLE HHS_CDC_HR.ATC_POSITION_INFO
(
	CASE_ID              NUMBER(10) NOT NULL ,
	POS_TTL              VARCHAR2(4000) NULL ,
	PAY_PLAN             VARCHAR2(4000) NULL ,
	SERIES               VARCHAR2(4000) NULL ,
	GRADE                VARCHAR2(100) NULL ,
	LOCATION             VARCHAR2(400) NULL ,
	LAST_NM              VARCHAR2(200) NULL ,
	FIRST_NM             VARCHAR2(200) NULL ,
	MIDDLE_INITIAL       VARCHAR2(200) NULL ,
	CNTRY_OF_CTZNSHP     VARCHAR2(200) NULL ,
	VISA_ASSSTNC_RQRD    VARCHAR2(200) NULL 
);



CREATE UNIQUE INDEX XPKATC_Position_Information ON HHS_CDC_HR.ATC_POSITION_INFO
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.ATC_POSITION_INFO
	ADD CONSTRAINT  XPKATC_Position_Information PRIMARY KEY (CASE_ID);



CREATE TABLE HHS_CDC_HR.ATC_SELECTED_BENEFITS
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	ENTTLD_BNFT          VARCHAR2(4000) NULL 
);



CREATE UNIQUE INDEX XPKATC_Selected_Entitled_Benef ON HHS_CDC_HR.ATC_SELECTED_BENEFITS
(CASE_ID   ASC,SEQ   ASC);



ALTER TABLE HHS_CDC_HR.ATC_SELECTED_BENEFITS
	ADD CONSTRAINT  XPKATC_Selected_Entitled_Benef PRIMARY KEY (CASE_ID,SEQ);



CREATE TABLE HHS_CDC_HR.ATC_VALIDATION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	STFFNG_NEED_VLDTD    VARCHAR2(100) NULL ,
	JSTFCTN_NOT_STFFNG_NEED_VLDTD VARCHAR2(4000) NULL ,
	PBMS_FUND_CNFRMD     VARCHAR2(100) NULL ,
	JSTFCTN_NOT_PBMS_FUND_CNFRMD VARCHAR2(4000) NULL ,
	HRNG_OPTNS_GID_RVWD  VARCHAR2(100) NULL ,
	JSTFCTN_NOT_HRNG_OPTNS_GID VARCHAR2(4000) NULL ,
	SLT_RQSTD            VARCHAR2(100) NULL ,
	JSTFCTN_NOT_SLT_RQSTD VARCHAR2(4000) NULL 
);



CREATE UNIQUE INDEX XPKNeed_And_Funding_Validation ON HHS_CDC_HR.ATC_VALIDATION
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.ATC_VALIDATION
	ADD CONSTRAINT  XPKNeed_And_Funding_Validation PRIMARY KEY (CASE_ID);



CREATE TABLE HHS_CDC_HR.AUTHORIZED_INCENTIVE
(
	CASE_ID              NUMBER(10) NOT NULL ,
	ANN_LEAVE_NON_FED_SVC VARCHAR2(10) NULL ,
	MOVING_EXP_ATHRZD    VARCHAR2(10) NULL ,
	RELOCATION_INC_ATHRZD VARCHAR2(10) NULL ,
	RECRUITMENT_INC_ATHRZD VARCHAR2(10) NULL ,
	STU_LOAN_REPAY_ATHRZD VARCHAR2(10) NULL ,
	OTHER_INC            VARCHAR2(4000) NULL 
);



CREATE UNIQUE INDEX XPK_AUTHORIZED_INCENTIVE ON HHS_CDC_HR.AUTHORIZED_INCENTIVE
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.AUTHORIZED_INCENTIVE
	ADD CONSTRAINT  XPK_AUTHORIZED_INCENTIVE PRIMARY KEY (CASE_ID);



CREATE TABLE HHS_CDC_HR.CLA_CONDITION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	PHYSICIAN_COMP_ALLWNC VARCHAR2(20) NULL ,
	DRUG_TEST_RQRD       VARCHAR2(20) NULL ,
	PRE_EMP_PHYSCL_RQRD  VARCHAR2(20) NULL ,
	SEL_AGNT_ACCSS_RQRD  VARCHAR2(20) NULL ,
	SUBJ_TO_ADDTNL_IDENTICAL VARCHAR2(20) NULL ,
	INCUMBENT_ONLY       VARCHAR2(20) NULL ,
	COMM_CORP_ELIGIBLE   VARCHAR2(20) NULL ,
	FINANCIAL_DSCLSR_RQRD VARCHAR2(20) NULL ,
	CYBER_SEC_CD         VARCHAR2(4000) NULL ,
	BUS_CD               VARCHAR2(4000) NULL ,
	ACQUISITION_CD       VARCHAR2(4000) NULL ,
	OPM_CERT_NO          VARCHAR2(400) NULL ,
	LMTD_TRM             VARCHAR2(100) NULL ,
	LMTD_EMRGNCY         VARCHAR2(100) NULL ,
	LMTD_TRM_NTE         VARCHAR2(100) NULL 
);



CREATE UNIQUE INDEX XPK_CLA_CONDITION ON HHS_CDC_HR.CLA_CONDITION
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.CLA_CONDITION
	ADD CONSTRAINT  XPK_CLA_CONDITION PRIMARY KEY (CASE_ID);



CREATE TABLE HHS_CDC_HR.CLA_STANDARD
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	STANDARD             VARCHAR2(400) NULL 
);



CREATE UNIQUE INDEX XPK_CLA_STANDARD ON HHS_CDC_HR.CLA_STANDARD
(CASE_ID   ASC,SEQ   ASC);



ALTER TABLE HHS_CDC_HR.CLA_STANDARD
	ADD CONSTRAINT  XPK_CLA_STANDARD PRIMARY KEY (CASE_ID,SEQ);



CREATE TABLE HHS_CDC_HR.CLASSIFICATION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	ADMN_CD              VARCHAR2(20) NULL ,
	ORG_NM               VARCHAR2(200) NULL ,
	HIRING_METHOD        VARCHAR2(20) NULL ,
	FIRST_SUBDVSN        VARCHAR2(200) NULL ,
	SECOND_SUBDVSN       VARCHAR2(200) NULL ,
	THIRD_SUBDVSN        VARCHAR2(200) NULL ,
	FOURTH_SUBDVSN       VARCHAR2(200) NULL ,
	FIFTH_SUBDVSN        VARCHAR2(200) NULL ,
	PROPOSED_ACTION      VARCHAR2(100) NULL ,
	PA_OTHER_DESC        VARCHAR2(400) NULL ,
	RQST_TP              VARCHAR2(100) NULL ,
	POS_STATUS           VARCHAR2(20) NULL ,
	EXSTING_PD_NO        VARCHAR2(200) NULL ,
	JOB_REQ_NO           VARCHAR2(200) NULL ,
	SO_NM                VARCHAR2(100) NULL ,
	SO_EMAIL             VARCHAR2(100) NULL ,
	CIO_ADMN_NM          VARCHAR2(100) NULL ,
	CIO_ADMN_EMAIL       VARCHAR2(100) NULL ,
	HRO_SPC_NM           VARCHAR2(100) NULL ,
	HRO_SPC_EMAIL        VARCHAR2(100) NULL ,
	CLA_SPC_NM           VARCHAR2(100) NULL ,
	CLA_SPC_EMAIL        VARCHAR2(100) NULL ,
	POS_BSD_MGMT_SYS_NO  VARCHAR2(100) NULL ,
	EXPLANATION          VARCHAR2(4000) NULL ,
	OFFCL_RSN_SBMSSN     VARCHAR2(400) NULL ,
	EMP_TP               VARCHAR2(200) NULL 
);



CREATE UNIQUE INDEX XPK_CLASSIFICATION ON HHS_CDC_HR.CLASSIFICATION
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.CLASSIFICATION
	ADD CONSTRAINT  XPK_CLASSIFICATION PRIMARY KEY (CASE_ID);



CREATE TABLE HHS_CDC_HR.CLASSIFIED_POS_TITLE
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	TITLE                VARCHAR2(4000) NULL 
);



CREATE UNIQUE INDEX XPKClassified_Position_Title ON HHS_CDC_HR.CLASSIFIED_POS_TITLE
(CASE_ID   ASC,SEQ   ASC);



ALTER TABLE HHS_CDC_HR.CLASSIFIED_POS_TITLE
	ADD CONSTRAINT  XPKClassified_Position_Title PRIMARY KEY (CASE_ID,SEQ);



CREATE TABLE HHS_CDC_HR.CONCURRENCE
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	SUPERVISOR_CERT      VARCHAR2(20) NULL ,
	SUPERVISOR_NM        VARCHAR2(100) NULL ,
	SUPERVISOR_APPRVL_DT VARCHAR2(20) NULL ,
	SUPERVISOR_TP        VARCHAR2(20) NULL 
);



CREATE UNIQUE INDEX XPK_CONCURRENCE ON HHS_CDC_HR.CONCURRENCE
(CASE_ID   ASC,SEQ   ASC);



ALTER TABLE HHS_CDC_HR.CONCURRENCE
	ADD CONSTRAINT  XPK_CONCURRENCE PRIMARY KEY (CASE_ID,SEQ);



CREATE TABLE HHS_CDC_HR.CONSIDERATION_AREA
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	CONSIDERATION        VARCHAR2(400) NULL ,
	CONSIDERATION_TP     VARCHAR2(400) NULL 
);



CREATE UNIQUE INDEX XPK_CONSIDERATION_AREA ON HHS_CDC_HR.CONSIDERATION_AREA
(CASE_ID   ASC,SEQ   ASC);



ALTER TABLE HHS_CDC_HR.CONSIDERATION_AREA
	ADD CONSTRAINT  XPK_CONSIDERATION_AREA PRIMARY KEY (CASE_ID,SEQ);



CREATE TABLE HHS_CDC_HR.DUTY_STATION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	STATION              VARCHAR2(400) NULL 
);



CREATE UNIQUE INDEX XPK_DUTY_STATION ON HHS_CDC_HR.DUTY_STATION
(CASE_ID   ASC,SEQ   ASC);



ALTER TABLE HHS_CDC_HR.DUTY_STATION
	ADD CONSTRAINT  XPK_DUTY_STATION PRIMARY KEY (CASE_ID,SEQ);



CREATE TABLE HHS_CDC_HR.EMP_CONDITION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	FINANCIAL_DSCLSR_RQRD VARCHAR2(10) NULL ,
	PRE_EMP_PHYSCL_RQRD  VARCHAR2(10) NULL ,
	DRG_TST_RQRD         VARCHAR2(10) NULL ,
	IMMUNZTN_RQRD        VARCHAR2(10) NULL ,
	MOBILITY_AGRMNT_RQRD VARCHAR2(10) NULL ,
	LIC_RQRD             VARCHAR2(10) NULL ,
	LIC_INFO             VARCHAR2(1000) NULL ,
	TRVL_RQRD            VARCHAR2(10) NULL ,
	DMSTC_TRVL_PRCNTG    VARCHAR2(100) NULL ,
	INTRNTNL_TRVL_PRCNTG VARCHAR2(100) NULL ,
	FOREIGN_LANG_RQRD    VARCHAR2(10) NULL ,
	OTHER_CON            VARCHAR2(4000) NULL 
);



CREATE UNIQUE INDEX XPK_EMP_CONDITION ON HHS_CDC_HR.EMP_CONDITION
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.EMP_CONDITION
	ADD CONSTRAINT  XPK_EMP_CONDITION PRIMARY KEY (CASE_ID);


CREATE TABLE HHS_CDC_HR.EXTERNAL_LINK_LOOKUP
(
	Link_ID              NUMBER(*,0) NOT NULL ,
	LINK_GROUP           NVARCHAR2(100) NULL ,
	LINK_URL             NVARCHAR2(1000) NULL ,
	LINK_DISPLAY         NVARCHAR2(100) NULL ,
	LINK_DESCRIPTION     NVARCHAR2(1000) NULL ,
	LINK_ACTIVE          CHAR(1) NULL ,
	LINK_EFFECTIVE_DT    DATE NULL ,
	LINK_EXPIRATION_DT   DATE NULL ,
	LINK_DISP_ORDER      NUMBER(38,0) NULL 
);



CREATE UNIQUE INDEX XPKExternal_Link_Lookup ON HHS_CDC_HR.EXTERNAL_LINK_LOOKUP
(Link_ID   ASC);



ALTER TABLE HHS_CDC_HR.EXTERNAL_LINK_LOOKUP
	ADD CONSTRAINT  XPKExternal_Link_Lookup PRIMARY KEY (Link_ID);



CREATE TABLE HHS_CDC_HR.FINANCIAL_STATEMENT
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	STATEMENT            VARCHAR2(400) NULL 
);



CREATE UNIQUE INDEX XPK_FINANCIAL_STATEMENT ON HHS_CDC_HR.FINANCIAL_STATEMENT
(CASE_ID   ASC,SEQ   ASC);



ALTER TABLE HHS_CDC_HR.FINANCIAL_STATEMENT
	ADD CONSTRAINT  XPK_FINANCIAL_STATEMENT PRIMARY KEY (CASE_ID,SEQ);



CREATE TABLE HHS_CDC_HR.GRADE
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	GRADE                VARCHAR2(100) NULL 
);



CREATE UNIQUE INDEX XPK_GRADE ON HHS_CDC_HR.GRADE
(CASE_ID   ASC,SEQ   ASC);



ALTER TABLE HHS_CDC_HR.GRADE
	ADD CONSTRAINT  XPK_GRADE PRIMARY KEY (CASE_ID,SEQ);



CREATE TABLE HHS_CDC_HR.GRADE_INFO
(
	CASE_ID              NUMBER(10) NOT NULL ,
	GRADE_SEQ            INTEGER NOT NULL ,
	FAIR_LABOR_STND_ACT  VARCHAR2(4000) NULL ,
	COMP_LVL_CD          VARCHAR2(4000) NULL ,
	PD_NO                VARCHAR2(200) NULL ,
	JOB_CD               VARCHAR2(200) NULL 
);



CREATE UNIQUE INDEX XPKGrade_Related_Information ON HHS_CDC_HR.GRADE_INFO
(CASE_ID   ASC,GRADE_SEQ   ASC);



ALTER TABLE HHS_CDC_HR.GRADE_INFO
	ADD CONSTRAINT  XPKGrade_Related_Information PRIMARY KEY (CASE_ID,GRADE_SEQ);



CREATE TABLE HHS_CDC_HR.HR_CASE
(
	CASE_ID              NUMBER(10) NOT NULL ,
	CASE_TP              VARCHAR2(20) NULL ,
	CREATOR_NM           VARCHAR2(100) NOT NULL ,
	CREATION_DT          TIMESTAMP NULL ,
	MODIFIER_NM          VARCHAR2(100) NULL ,
	MODIFICATION_DT      TIMESTAMP NULL 
);



CREATE UNIQUE INDEX XPKHR_Case ON HHS_CDC_HR.HR_CASE
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.HR_CASE
	ADD CONSTRAINT  XPKHR_Case PRIMARY KEY (CASE_ID);



CREATE TABLE HHS_CDC_HR.LANGUAGE
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	LANG                 VARCHAR2(100) NULL 
);



CREATE UNIQUE INDEX XPK_LANGUAGE ON HHS_CDC_HR.LANGUAGE
(CASE_ID   ASC,SEQ   ASC);



ALTER TABLE HHS_CDC_HR.LANGUAGE
	ADD CONSTRAINT  XPK_LANGUAGE PRIMARY KEY (CASE_ID,SEQ);



CREATE TABLE HHS_CDC_HR.POS_TITLE_SERIES
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	OFFICIAL_POS_TTL     VARCHAR2(4000) NULL ,
	SERIES               VARCHAR2(4000) NULL 
);



CREATE UNIQUE INDEX XPKPosition_Title_Series ON HHS_CDC_HR.POS_TITLE_SERIES
(CASE_ID   ASC,SEQ   ASC);



ALTER TABLE HHS_CDC_HR.POS_TITLE_SERIES
	ADD CONSTRAINT  XPKPosition_Title_Series PRIMARY KEY (CASE_ID,SEQ);



CREATE TABLE HHS_CDC_HR.POSITION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	JOB_REQ_NO           VARCHAR2(100) NULL ,
	ORG_POS_TTL          VARCHAR2(4000) NULL ,
	FNCTNL_POS_TTL       VARCHAR2(4000) NULL ,
	PAY_PLAN             VARCHAR2(4000) NULL ,
	PROMO_POTENTIAL      VARCHAR2(400) NULL ,
	POS_SENSITIVITY      VARCHAR2(4000) NULL ,
	FULL_PERF_LVL        VARCHAR2(400) NULL ,
	POS_TP               VARCHAR2(400) NULL ,
	COMMON_ACCT_NO       VARCHAR2(400) NULL ,
	BACKFILL_VC          VARCHAR2(400) NULL ,
	BACKFILL_VC_NM       VARCHAR2(400) NULL ,
	BACKFILL_VC_RSN      VARCHAR2(1000) NULL ,
	NUM_OF_VACANCY       VARCHAR2(400) NULL ,
	APPOINTMENT_TP       VARCHAR2(400) NULL ,
	NOT_TO_EXCEED        VARCHAR2(400) NULL ,
	NAME_REQUEST         VARCHAR2(400) NULL ,
	POS_OPEN_CONT        VARCHAR2(400) NULL ,
	NUM_OF_DAYS_AD       VARCHAR2(400) NULL ,
	WORK_SCH_TP          VARCHAR2(400) NULL ,
	HRS_PER_WEEK         VARCHAR2(400) NULL ,
	REMARKS              VARCHAR2(4000) NULL ,
	SERVICE              VARCHAR2(400) NULL ,
	EMPLOYING_OFF_LOC    VARCHAR2(400) NULL 
);



CREATE UNIQUE INDEX XPK_POSITION ON HHS_CDC_HR.POSITION
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.POSITION
	ADD CONSTRAINT  XPK_POSITION PRIMARY KEY (CASE_ID);



CREATE TABLE HHS_CDC_HR.POSITION_BUILD_APPROVAL
(
	CASE_ID              NUMBER(10) NOT NULL ,
	ACTV_N_ACCRT         VARCHAR2(100) NULL ,
	ALL_SIGN_OF8         VARCHAR2(100) NULL ,
	CAPHR_POS_NO         VARCHAR2(100) NULL ,
	JOB_CODE             VARCHAR2(100) NULL ,
	BUS_ARRVD            VARCHAR2(100) NULL ,
	SPRVSRY_STTS_APPRVD  VARCHAR2(100) NULL ,
	FLSA_APPRVD          VARCHAR2(100) NULL ,
	ADMIN_CD_APPRVD      VARCHAR2(100) NULL ,
	PM_STWRD_NM          VARCHAR2(100) NULL ,
	PM_STWRD_APPRVD      VARCHAR2(100) NULL 
);



CREATE UNIQUE INDEX XPKPosition_Build_Approval ON HHS_CDC_HR.POSITION_BUILD_APPROVAL
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.POSITION_BUILD_APPROVAL
	ADD CONSTRAINT  XPKPosition_Build_Approval PRIMARY KEY (CASE_ID);



CREATE TABLE HHS_CDC_HR.REC_SME
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	NAME                 VARCHAR2(200) NULL ,
	EMAIL                VARCHAR2(100) NULL ,
	SME_TP               VARCHAR2(10) NULL ,
	IS_PRIMARY           VARCHAR2(10) NULL ,
	ORG_NM               VARCHAR2(200) NULL 
);



CREATE UNIQUE INDEX XPK_REC_SME ON HHS_CDC_HR.REC_SME
(CASE_ID   ASC,SEQ   ASC);



ALTER TABLE HHS_CDC_HR.REC_SME
	ADD CONSTRAINT  XPK_REC_SME PRIMARY KEY (CASE_ID,SEQ);



CREATE TABLE HHS_CDC_HR.RECRUITMENT
(
	CASE_ID              NUMBER(10) NOT NULL ,
	RQST_TP              VARCHAR2(100) NULL ,
	ADMN_CD              VARCHAR2(20) NULL ,
	ORG_NM               VARCHAR2(200) NULL ,
	HIRING_MTHD          VARCHAR2(20) NULL ,
	SO_NM                VARCHAR2(100) NULL ,
	SO_EML               VARCHAR2(100) NULL ,
	CIO_ADMN_NM          VARCHAR2(100) NULL ,
	CIO_ADMN_EML         VARCHAR2(100) NULL ,
	HRO_SPC_NM           VARCHAR2(100) NULL ,
	HRO_SPC_EML          VARCHAR2(100) NULL ,
	CLA_SPC_NM           VARCHAR2(100) NULL ,
	CLA_SPC_EML          VARCHAR2(100) NULL ,
	COM_CHR_NM           VARCHAR2(100) NULL ,
	COM_CHR_EML          VARCHAR2(100) NULL ,
	COM_CHR_ORG_NM       VARCHAR2(200) NULL ,
	SME_RQRD             VARCHAR2(10) NULL ,
	STFFNG_NEED_VLDTD    VARCHAR2(10) NULL ,
	JSTFCTN_NOT_VLD_STAFF_ND VARCHAR2(4000) NULL ,
	HIRING_OPT_GUIDE_RVWD VARCHAR2(10) NULL ,
	JSTFCTN_NOT_RVWNG_HR_OPT_GD VARCHAR2(4000) NULL ,
	POS_BSD_MGMT_SYS_NO  VARCHAR2(100) NULL ,
	REQ_APPRVD_BY_HHS    VARCHAR2(10) NULL ,
	JSTFCTN_NOT_RCVNG_HHS_APPRL VARCHAR2(4000) NULL ,
	SLOT_RQSTD           VARCHAR2(10) NULL ,
	JSTFCTN_NOT_RCVNG_SLOT VARCHAR2(4000) NULL 
);



CREATE UNIQUE INDEX XPK_RECRUITMENT ON HHS_CDC_HR.RECRUITMENT
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.RECRUITMENT
	ADD CONSTRAINT  XPK_RECRUITMENT PRIMARY KEY (CASE_ID);


CREATE TABLE HHS_CDC_HR.TSA_PROCESSING
(
	CASE_ID              NUMBER(10) NOT NULL ,
	TSA_PRCSSR_NM        VARCHAR2(200) NULL ,
	TSA_PRCSSR_APPRVL_DT VARCHAR2(100) NULL ,
	ADDTNL_APPRVL_RQRD   VARCHAR2(20) NULL ,
	ADDTNL_TSA_PRCSSR_NM VARCHAR2(200) NULL ,
	ADDTNL_TSA_PRCSSR_EMAIL VARCHAR2(200) NULL ,
	LEAD_TSA_PRCSSR_NM   VARCHAR2(200) NULL ,
	LEAD_TSA_PRCSSR_APPRVL_DT VARCHAR2(20) NULL ,
	DOC_SCANNED_TO_EOPF  VARCHAR2(100) NULL ,
	QLTY_ASSRNC_RVW_CMPL VARCHAR2(100) NULL 
);



CREATE UNIQUE INDEX XPKTSA_Processing ON HHS_CDC_HR.TSA_PROCESSING
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.TSA_PROCESSING
	ADD CONSTRAINT  XPKTSA_Processing PRIMARY KEY (CASE_ID);



CREATE TABLE HHS_CDC_HR.VALIDATION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	PRE_RECRUITMENT_MTNG_DT VARCHAR2(20) NULL ,
	PPP_PCP_CLRD         VARCHAR2(10) NULL ,
	PPP_PCP_CLRD_DT      VARCHAR2(20) NULL ,
	JUSTFCTN_PPP_PCP_NOT_CLEARED VARCHAR2(4000) NULL 
);



CREATE UNIQUE INDEX XPK_VALIDATION ON HHS_CDC_HR.VALIDATION
(CASE_ID   ASC);



ALTER TABLE HHS_CDC_HR.VALIDATION
	ADD CONSTRAINT  XPK_VALIDATION PRIMARY KEY (CASE_ID);



ALTER TABLE HHS_CDC_HR.APP_APPROVAL
	ADD (CONSTRAINT R_50 FOREIGN KEY (CASE_ID) REFERENCES APPOINTMENT (CASE_ID));



ALTER TABLE HHS_CDC_HR.APP_TRACKING
	ADD (CONSTRAINT R_49 FOREIGN KEY (CASE_ID) REFERENCES APPOINTMENT (CASE_ID));



ALTER TABLE HHS_CDC_HR.APPOINTMENT
	ADD (CONSTRAINT R_39 FOREIGN KEY (CASE_ID) REFERENCES HR_CASE (CASE_ID));



ALTER TABLE HHS_CDC_HR.ATC_BENEFITS
	ADD (CONSTRAINT R_48 FOREIGN KEY (CASE_ID) REFERENCES APPOINTMENT (CASE_ID));



ALTER TABLE HHS_CDC_HR.ATC_COMPENSATION
	ADD (CONSTRAINT R_45 FOREIGN KEY (CASE_ID) REFERENCES APPOINTMENT (CASE_ID));



ALTER TABLE HHS_CDC_HR.ATC_NATURE_OF_ACTION
	ADD (CONSTRAINT R_46 FOREIGN KEY (CASE_ID) REFERENCES ATC_PERSONNEL_ACTION (CASE_ID));



ALTER TABLE HHS_CDC_HR.ATC_PERSONNEL_ACTION
	ADD (CONSTRAINT R_44 FOREIGN KEY (CASE_ID) REFERENCES APPOINTMENT (CASE_ID));



ALTER TABLE HHS_CDC_HR.ATC_POSITION_INFO
	ADD (CONSTRAINT R_42 FOREIGN KEY (CASE_ID) REFERENCES APPOINTMENT (CASE_ID));



ALTER TABLE HHS_CDC_HR.ATC_SELECTED_BENEFITS
	ADD (CONSTRAINT R_53 FOREIGN KEY (CASE_ID) REFERENCES ATC_BENEFITS (CASE_ID));



ALTER TABLE HHS_CDC_HR.ATC_VALIDATION
	ADD (CONSTRAINT R_41 FOREIGN KEY (CASE_ID) REFERENCES APPOINTMENT (CASE_ID));



ALTER TABLE HHS_CDC_HR.AUTHORIZED_INCENTIVE
	ADD (CONSTRAINT FK_RECRUITMENT_AUTH_INCENTIVE FOREIGN KEY (CASE_ID) REFERENCES RECRUITMENT (CASE_ID));



ALTER TABLE HHS_CDC_HR.CLA_CONDITION
	ADD (CONSTRAINT FK_CLASSIFICATION_CONDITION FOREIGN KEY (CASE_ID) REFERENCES CLASSIFICATION (CASE_ID));



ALTER TABLE HHS_CDC_HR.CLA_STANDARD
	ADD (CONSTRAINT FK_CLA_CONDITION_STANDARD FOREIGN KEY (CASE_ID) REFERENCES CLA_CONDITION (CASE_ID));



ALTER TABLE HHS_CDC_HR.CLASSIFICATION
	ADD (CONSTRAINT FK_HR_CASE_CLASSIFICATION FOREIGN KEY (CASE_ID) REFERENCES HR_CASE (CASE_ID));



ALTER TABLE HHS_CDC_HR.CLASSIFIED_POS_TITLE
	ADD (CONSTRAINT R_36 FOREIGN KEY (CASE_ID) REFERENCES POSITION (CASE_ID));



ALTER TABLE HHS_CDC_HR.CONCURRENCE
	ADD (CONSTRAINT FK_CLASSIFICATION_CONCURRENCE FOREIGN KEY (CASE_ID) REFERENCES CLASSIFICATION (CASE_ID));



ALTER TABLE HHS_CDC_HR.CONSIDERATION_AREA
	ADD (CONSTRAINT FK_POSITION_CONSIDERATION_AREA FOREIGN KEY (CASE_ID) REFERENCES POSITION (CASE_ID));



ALTER TABLE HHS_CDC_HR.DUTY_STATION
	ADD (CONSTRAINT FK_POSITION_DUTY_STATION FOREIGN KEY (CASE_ID) REFERENCES POSITION (CASE_ID));



ALTER TABLE HHS_CDC_HR.EMP_CONDITION
	ADD (CONSTRAINT FK_RECRUITMENT_EMP_CONDITION FOREIGN KEY (CASE_ID) REFERENCES RECRUITMENT (CASE_ID));



ALTER TABLE HHS_CDC_HR.FINANCIAL_STATEMENT
	ADD (CONSTRAINT R_34 FOREIGN KEY (CASE_ID) REFERENCES HR_CASE (CASE_ID));



ALTER TABLE HHS_CDC_HR.GRADE
	ADD (CONSTRAINT FK_POSITION_GRADE FOREIGN KEY (CASE_ID) REFERENCES POSITION (CASE_ID));



ALTER TABLE HHS_CDC_HR.GRADE_INFO
	ADD (CONSTRAINT R_38 FOREIGN KEY (CASE_ID, GRADE_SEQ) REFERENCES GRADE (CASE_ID, SEQ));



ALTER TABLE HHS_CDC_HR.LANGUAGE
	ADD (CONSTRAINT FK_EMP_CONDITION_LANGUAGE FOREIGN KEY (CASE_ID) REFERENCES EMP_CONDITION (CASE_ID));



ALTER TABLE HHS_CDC_HR.POS_TITLE_SERIES
	ADD (CONSTRAINT R_37 FOREIGN KEY (CASE_ID) REFERENCES POSITION (CASE_ID));



ALTER TABLE HHS_CDC_HR.POSITION
	ADD (CONSTRAINT FK_HR_CASE_POSITION FOREIGN KEY (CASE_ID) REFERENCES HR_CASE (CASE_ID));



ALTER TABLE HHS_CDC_HR.POSITION_BUILD_APPROVAL
	ADD (CONSTRAINT R_51 FOREIGN KEY (CASE_ID) REFERENCES APPOINTMENT (CASE_ID));



ALTER TABLE HHS_CDC_HR.REC_SME
	ADD (CONSTRAINT FK_RECRUITMENT_REC_SME FOREIGN KEY (CASE_ID) REFERENCES RECRUITMENT (CASE_ID));



ALTER TABLE HHS_CDC_HR.RECRUITMENT
	ADD (CONSTRAINT FK_HR_CASE_RECRUITMENT FOREIGN KEY (CASE_ID) REFERENCES HR_CASE (CASE_ID));



ALTER TABLE HHS_CDC_HR.TSA_PROCESSING
	ADD (CONSTRAINT R_52 FOREIGN KEY (CASE_ID) REFERENCES APPOINTMENT (CASE_ID));



ALTER TABLE HHS_CDC_HR.VALIDATION
	ADD (CONSTRAINT FK_RECRUITMENT_VALIDATION FOREIGN KEY (CASE_ID) REFERENCES RECRUITMENT (CASE_ID));

