--------------------------------------------------------
--  File created - Friday-August-31-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CDC_FORM_DATA_SEQ
--------------------------------------------------------
/*
DROP SEQUENCE "HHS_CDC_HR"."CDC_FORM_DATA_SEQ";
/
DROP SEQUENCE "HHS_CDC_HR"."ERROR_LOG_SEQ";
/
DROP SEQUENCE "HHS_CDC_HR"."TBL_FORM_DTL_AUDIT_SEQ";
/

CREATE SEQUENCE  "HHS_CDC_HR"."CDC_FORM_DATA_SEQ"  MINVALUE 1 NOMAXVALUE NOCYCLE NOCACHE INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
/
CREATE SEQUENCE  "HHS_CDC_HR"."ERROR_LOG_SEQ"  MINVALUE 1 NOMAXVALUE NOCYCLE NOCACHE INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
/
CREATE SEQUENCE  "HHS_CDC_HR"."TBL_FORM_DTL_AUDIT_SEQ"  MINVALUE 1 NOMAXVALUE NOCYCLE NOCACHE INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
/
*/