------------------------------------------------------------------------------------------
--  Name	            : 	6_grant_cdc_hr.sql
--	Author				:	Taeho Lee <thee@bizflow.com>
--	Copyright			:	BizFlow Corp.	
--	
--	Project				:	HHS CDC HR Workflow Solution - EWITS 2.0
--	Purpose				:	Grant tables access to CDC database roles
--	
--  Example
--  To use in SQL statements:
--
-- 	WHEN		WHO			WHAT		
-- 	-----------	--------	-------------------------------------------------------
-- 	04/13/2018	THLEE		Created
------------------------------------------------------------------------------------------

-- Tables
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.APP_APPROVAL TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.APP_APPROVAL TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.APP_TRACKING TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.APP_TRACKING TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.APPOINTMENT TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.APPOINTMENT TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ATC_BENEFITS TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ATC_BENEFITS TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ATC_COMPENSATION TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ATC_COMPENSATION TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ATC_NATURE_OF_ACTION TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ATC_NATURE_OF_ACTION TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ATC_PERSONNEL_ACTION TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ATC_PERSONNEL_ACTION TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ATC_POSITION_INFO TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ATC_POSITION_INFO TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ATC_SELECTED_BENEFITS TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ATC_SELECTED_BENEFITS TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ATC_VALIDATION TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ATC_VALIDATION TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.AUTHORIZED_INCENTIVE TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.AUTHORIZED_INCENTIVE TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.CLA_CONDITION TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.CLA_CONDITION TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.CLA_STANDARD TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.CLA_STANDARD TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.CLASSIFICATION TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.CLASSIFICATION TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.CLASSIFIED_POS_TITLE TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.CLASSIFIED_POS_TITLE TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.CONCURRENCE TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.CONCURRENCE TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.CONSIDERATION_AREA TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.CONSIDERATION_AREA TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.DUTY_STATION TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.DUTY_STATION TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.EMP_CONDITION TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.EMP_CONDITION TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.FINANCIAL_STATEMENT TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.FINANCIAL_STATEMENT TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.GRADE TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.GRADE TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.GRADE_INFO TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.GRADE_INFO TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.LANGUAGE TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.LANGUAGE TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.POS_TITLE_SERIES TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.POS_TITLE_SERIES TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.POSITION TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.POSITION TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.POSITION_BUILD_APPROVAL TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.POSITION_BUILD_APPROVAL TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.REC_SME TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.REC_SME TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.RECRUITMENT TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.RECRUITMENT TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.TSA_PROCESSING TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.TSA_PROCESSING TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.VALIDATION TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.VALIDATION TO HHS_CDC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.HR_CASE TO HHS_CDC_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.HR_CASE TO HHS_CDC_HR_RW_ROLE;

-- Base Tables
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.TBL_FORM_DTL TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.TBL_FORM_DTL TO HHS_CDC_HR_DEV_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.TBL_FORM_DTL_AUDIT TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.TBL_FORM_DTL_AUDIT TO HHS_CDC_HR_DEV_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.TBL_LOOKUP TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.TBL_LOOKUP TO HHS_CDC_HR_DEV_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.VALIDATION TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.VALIDATION TO HHS_CDC_HR_DEV_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.EXTERNAL_LINK_LOOKUP TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.EXTERNAL_LINK_LOOKUP TO HHS_CDC_HR_DEV_ROLE;

--Added 10/26/2018 - BEGIN
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ERA_LOG_CAPHR_PAR TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ERA_LOG_CAPHR_PAR TO HHS_CDC_HR_DEV_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ERA_LOG_CAPHR_JR TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ERA_LOG_CAPHR_JR TO HHS_CDC_HR_DEV_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ERA_LOG_CAPHR_LAST_RUN TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ERA_LOG_CAPHR_LAST_RUN TO HHS_CDC_HR_DEV_ROLE;
--Added 10/26/2018 - END

--Added 10/29/2018 - BEGIN
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.NAMED_ACTION TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.NAMED_ACTION TO HHS_CDC_HR_DEV_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.CAPHR_INFO TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.CAPHR_INFO TO HHS_CDC_HR_DEV_ROLE;
--Added 10/29/2018 - END

-- Views
--GRANT SELECT ON HHS_CDC_HR.V_TBL_LOOKUP TO HHS_CDC_HR_RW_ROLE;
--GRANT SELECT ON HHS_CDC_HR.V_TBL_LOOKUP TO HHS_CDC_HR_DEV_ROLE;

--Grant Business Tables in HHS_CDC_HR
--GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CDC_HR.APPROVALS TO HHS_CDC_HR_DEV_ROLE;
--GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CDC_HR.APPROVALS TO HHS_CDC_HR_RW_ROLE;

--Grant Function or Sequence
GRANT EXECUTE ON HHS_CDC_HR.FN_CONCAT_HR_RECORDS TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_CONCAT_HR_RECORDS TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.FN_GET_FORM_DATA_FIELD_VALUE TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_GET_FORM_DATA_FIELD_VALUE TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.FN_GET_XML_FIELD_VALUE TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_GET_XML_FIELD_VALUE TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.FN_PARSENAME TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_PARSENAME TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.FN_GET_ACT_CMPLTUSR TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_GET_ACT_CMPLTUSR TO HHS_CDC_HR_DEV_ROLE;


--Grant Stored Procedure
GRANT EXECUTE ON HHS_CDC_HR.SP_CLEAN_FORM_RECORDS TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_CLEAN_FORM_RECORDS TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.SP_DATACOPY_FORM_DATA TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_DATACOPY_FORM_DATA TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.SP_DATACOPY_FORM_DATA TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_DATACOPY_FORM_DATA TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_APPOINTMENT_TBLS TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_APPOINTMENT_TBLS TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_CLASSIFICATION_TBLS TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_CLASSIFICATION_TBLS TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_FORM_DATA TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_FORM_DATA TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_RECRUITMENT_TBLS TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_RECRUITMENT_TBLS TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_NAMEDACTION_TBLS TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_NAMEDACTION_TBLS TO HHS_CDC_HR_DEV_ROLE;

