------------------------------------------------------------------------------------------
--  Name	            : 	4_table.sql
--	Author				:	Taeho Lee <thee@bizflow.com>
--	Copyright			:	BizFlow Corp.	
--	
--	Project				:	HHS CDC HR Workflow Solution - EWITS 2.0
--	Purpose				:	Create HHS_CDC_HR database tables
--	
--  Example
--  To use in SQL statements:
--
-- 	WHEN		WHO			WHAT		
-- 	-----------	--------	-------------------------------------------------------
-- 	04/13/2018	THLEE		Created
------------------------------------------------------------------------------------------

CREATE TABLE HHS_CDC_HR.AUTHORIZED_INCENTIVE
(
	CASE_ID              NUMBER(10) NOT NULL ,
	ANN_LEAVE_NON_FED_SVC VARCHAR2(10) NULL ,
	MOVING_EXP_ATHRZD    VARCHAR2(10) NULL ,
	RELOCATION_INC_ATHRZD VARCHAR2(10) NULL ,
	RECRUITMENT_INC_ATHRZD VARCHAR2(10) NULL ,
	STU_LOAN_REPAY_ATHRZD VARCHAR2(10) NULL ,
	OTHER_INC            VARCHAR2(4000) NULL 
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPK_AUTHORIZED_INCENTIVE ON HHS_CDC_HR.AUTHORIZED_INCENTIVE
(CASE_ID   ASC);


CREATE TABLE HHS_CDC_HR.CLA_CONDITION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	PHYSICIAN_COMP_ALLWNC VARCHAR2(20) NULL ,
	DRUG_TEST_RQRD       VARCHAR2(20) NULL ,
	PRE_EMP_PHYSCL_RQRD  VARCHAR2(20) NULL ,
	SEL_AGNT_ACCSS_RQRD  VARCHAR2(20) NULL ,
	SUBJ_TO_ADDTNL_IDENTICAL VARCHAR2(20) NULL ,
	INCUMBENT_ONLY       VARCHAR2(20) NULL ,
	COMM_CORP_ELIGIBLE   VARCHAR2(20) NULL ,
	FINANCIAL_DSCLSR_RQRD VARCHAR2(20) NULL ,
	FAIR_LABOR_STND_ACT  VARCHAR2(4000) NULL ,
	CYBER_SEC_CD         VARCHAR2(4000) NULL ,
	BUS_CD               VARCHAR2(4000) NULL ,
	ACQUISITION_CD       VARCHAR2(4000) NULL ,
	COMP_LVL_CD          VARCHAR2(4000) NULL ,
    OPM_CERT_NO          VARCHAR2(400) NULL
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPK_CLA_CONDITION ON HHS_CDC_HR.CLA_CONDITION
(CASE_ID   ASC);



CREATE TABLE HHS_CDC_HR.CLA_STANDARD
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	STANDARD             VARCHAR2(400) NULL 
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPK_CLA_STANDARD ON HHS_CDC_HR.CLA_STANDARD
(CASE_ID   ASC, SEQ   ASC);



CREATE TABLE HHS_CDC_HR.CLASSIFICATION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	ADMN_CD              VARCHAR2(20) NULL ,
	ORG_NM               VARCHAR2(200) NULL ,
	HIRING_METHOD        VARCHAR2(20) NULL ,
	FIRST_SUBDVSN        VARCHAR2(200) NULL ,
	SECOND_SUBDVSN       VARCHAR2(200) NULL ,
	THIRD_SUBDVSN        VARCHAR2(200) NULL ,
	FOURTH_SUBDVSN       VARCHAR2(200) NULL ,
	FIFTH_SUBDVSN        VARCHAR2(200) NULL ,
	SUBMISSION_RSN       VARCHAR2(100) NULL ,
	OTHER_SBMSSN_RSN_DSC VARCHAR2(400) NULL ,
    RQST_TP              VARCHAR2(100) NULL ,
	POS_STATUS           VARCHAR2(20) NULL ,
	EXSTING_PD_NO        VARCHAR2(200) NULL ,
	JOB_REQ_NO           VARCHAR2(200) NULL ,
	SO_NM                VARCHAR2(100) NULL ,
	SO_EMAIL             VARCHAR2(100) NULL ,
	CIO_ADMN_NM          VARCHAR2(100) NULL ,
	CIO_ADMN_EMAIL       VARCHAR2(100) NULL ,
	HRO_SPC_NM           VARCHAR2(100) NULL ,
	HRO_SPC_EMAIL        VARCHAR2(100) NULL ,
	CLA_SPC_NM           VARCHAR2(100) NULL ,
	CLA_SPC_EMAIL        VARCHAR2(100) NULL ,
    POS_BSD_MGMT_SYS_NO  VARCHAR2(100) NULL ,
    EXPLANATION          VARCHAR2(4000) NULL ,
    OFFCL_RSN_SBMSSN     VARCHAR2(400) NULL
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPK_CLASSIFICATION ON HHS_CDC_HR.CLASSIFICATION
(CASE_ID   ASC);



CREATE TABLE HHS_CDC_HR.CLASSIFIED_POS_TITLE
(
   CASE_ID              NUMBER(10) NOT NULL,
   SEQ                  INTEGER NOT NULL ,
   TITLE               VARCHAR2(4000) NULL

);

ALTER TABLE HHS_CDC_HR.CLASSIFIED_POS_TITLE
   ADD CONSTRAINT  XPKClassified_Position_Title PRIMARY KEY (CASE_ID,SEQ);


CREATE TABLE HHS_CDC_HR.CONCURRENCE
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	SUPERVISOR_CERT      VARCHAR2(20) NULL ,
	SUPERVISOR_NM        VARCHAR2(100) NULL ,
	SUPERVISOR_APPRVL_DT VARCHAR2(20) NULL ,
	SUPERVISOR_TP        VARCHAR2(20) NULL 
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPK_CONCURRENCE ON HHS_CDC_HR.CONCURRENCE
(CASE_ID   ASC,SEQ   ASC);



CREATE  INDEX HHS_CDC_HR.XIF1_CONCURRENCE ON HHS_CDC_HR.CONCURRENCE
(CASE_ID   ASC);



CREATE TABLE HHS_CDC_HR.CONSIDERATION_AREA
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	CONSIDERATION        VARCHAR2(400) NULL ,
    CONSIDERATION_TP     VARCHAR2(400) NULL
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPK_CONSIDERATION_AREA ON HHS_CDC_HR.CONSIDERATION_AREA
(CASE_ID   ASC,SEQ   ASC);



CREATE  INDEX HHS_CDC_HR.XIF1_CONSIDERATION_AREA ON HHS_CDC_HR.CONSIDERATION_AREA
(CASE_ID   ASC);



CREATE TABLE HHS_CDC_HR.DUTY_STATION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	STATION              VARCHAR2(400) NULL 
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPK_DUTY_STATION ON HHS_CDC_HR.DUTY_STATION
(CASE_ID   ASC,SEQ   ASC);



CREATE  INDEX HHS_CDC_HR.XIF1_DUTY_STATION ON HHS_CDC_HR.DUTY_STATION
(CASE_ID   ASC);



CREATE TABLE HHS_CDC_HR.EMP_CONDITION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	FINANCIAL_DSCLSR_RQRD VARCHAR2(10) NULL ,
	PRE_EMP_PHYSCL_RQRD  VARCHAR2(10) NULL ,
	DRG_TST_RQRD         VARCHAR2(10) NULL ,
	IMMUNZTN_RQRD        VARCHAR2(10) NULL ,
	MOBILITY_AGRMNT_RQRD VARCHAR2(10) NULL ,
	LIC_RQRD             VARCHAR2(10) NULL ,
	LIC_INFO             VARCHAR2(1000) NULL ,
	TRVL_RQRD            VARCHAR2(10) NULL ,
	DMSTC_TRVL_PRCNTG    VARCHAR2(100) NULL ,
	INTRNTNL_TRVL_PRCNTG VARCHAR2(100) NULL ,
	FOREIGN_LANG_RQRD    VARCHAR2(10) NULL ,
	OTHER_CON            VARCHAR2(4000) NULL 
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPK_EMP_CONDITION ON HHS_CDC_HR.EMP_CONDITION
(CASE_ID   ASC);



CREATE TABLE HHS_CDC_HR.FINANCIAL_STATEMENT
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	STATEMENT            VARCHAR2(400) NULL 
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPK_FINANCIAL_STATEMENT ON HHS_CDC_HR.FINANCIAL_STATEMENT
(CASE_ID, SEQ   ASC);



CREATE TABLE HHS_CDC_HR.GRADE
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	GRADE                VARCHAR2(100) NULL 
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPK_GRADE ON HHS_CDC_HR.GRADE
(CASE_ID   ASC,SEQ   ASC);



CREATE  INDEX HHS_CDC_HR.XIF1_GRADE ON HHS_CDC_HR.GRADE
(CASE_ID   ASC);


CREATE TABLE HHS_CDC_HR.POS_TITLE_SERIES
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
	OFFICIAL_POS_TTL     VARCHAR2(4000) NULL ,
    SERIES               VARCHAR2(4000) NULL
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPK_POS_TITLE_SERIES ON HHS_CDC_HR.POS_TITLE_SERIES
(CASE_ID   ASC,SEQ   ASC);



CREATE  INDEX HHS_CDC_HR.XIF1_POS_TITLE_SERIES ON HHS_CDC_HR.POS_TITLE_SERIES
(CASE_ID   ASC);



CREATE TABLE HHS_CDC_HR.HR_CASE
(
	CASE_ID              NUMBER(10) NOT NULL ,
    CASE_TP              VARCHAR2(20) NULL ,
	CREATOR_NM           VARCHAR2(100) NULL ,
	CREATION_DT          TIMESTAMP NULL, 
	MODIFIER_NM          VARCHAR2(100) NULL ,
	MODIFICATION_DT      TIMESTAMP NULL 
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPKHR_Case ON HHS_CDC_HR.HR_CASE
(CASE_ID   ASC);



CREATE TABLE HHS_CDC_HR.LANGUAGE
(
	CASE_ID              NUMBER(10) NOT NULL ,
    SEQ                  INTEGER NOT NULL ,
	LANG                 VARCHAR2(100) NULL 
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPK_LANGUAGE ON HHS_CDC_HR.LANGUAGE
(CASE_ID   ASC, SEQ ASC);



CREATE TABLE HHS_CDC_HR.POSITION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	JOB_REQ_NO           VARCHAR2(100) NULL ,
	OFFICIAL_POS_TTL     VARCHAR2(4000) NULL ,
	ORG_POS_TTL          VARCHAR2(4000) NULL ,
	CLSSFD_POS_TTL       VARCHAR2(4000) NULL ,
	FNCTNL_POS_TTL       VARCHAR2(4000) NULL ,
	PAY_PLAN             VARCHAR2(4000) NULL ,
	SERIES               VARCHAR2(4000) NULL ,
	PROMO_POTENTIAL      VARCHAR2(400) NULL ,
	POS_SENSITIVITY      VARCHAR2(4000) NULL ,
	FULL_PERF_LVL        VARCHAR2(400) NULL ,
	POS_TP               VARCHAR2(400) NULL ,
	COMMON_ACCT_NO       VARCHAR2(400) NULL ,
	BACKFILL_VC          VARCHAR2(400) NULL ,
	BACKFILL_VC_NM       VARCHAR2(400) NULL ,
	BACKFILL_VC_RSN      VARCHAR2(1000) NULL ,
	NUM_OF_VACANCY       VARCHAR2(400) NULL ,
	APPOINTMENT_TP       VARCHAR2(400) NULL ,
	NOT_TO_EXCEED        VARCHAR2(400) NULL ,
	NAME_REQUEST         VARCHAR2(400) NULL ,
	POS_OPEN_CONT        VARCHAR2(400) NULL ,
	NUM_OF_DAYS_AD       VARCHAR2(400) NULL ,
	WORK_SCH_TP          VARCHAR2(400) NULL ,
	HRS_PER_WEEK         VARCHAR2(400) NULL ,
	REMARKS              VARCHAR2(4000) NULL ,
	SERVICE              VARCHAR2(400) NULL ,
	EMPLOYING_OFF_LOC    VARCHAR2(400) NULL 
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPK_POSITION ON HHS_CDC_HR.POSITION
(CASE_ID   ASC);



CREATE TABLE HHS_CDC_HR.REC_SME
(
	CASE_ID              NUMBER(10) NOT NULL ,
	SEQ                  INTEGER NOT NULL ,
    NAME                 VARCHAR2(200) NULL ,
	EMAIL                VARCHAR2(100) NULL ,
	SME_TP               VARCHAR2(10) NULL ,
	IS_PRIMARY           VARCHAR2(10) NULL ,
	ORG_NM               VARCHAR2(200) NULL 
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPK_REC_SME ON HHS_CDC_HR.REC_SME
(CASE_ID   ASC,SEQ   ASC);



CREATE  INDEX HHS_CDC_HR.XIF1_REC_SME ON HHS_CDC_HR.REC_SME
(CASE_ID   ASC);



CREATE TABLE HHS_CDC_HR.RECRUITMENT
(
	CASE_ID              NUMBER(10) NOT NULL ,
	ADMN_CD              VARCHAR2(20) NULL ,
	ORG_NM               VARCHAR2(200) NULL ,
	HIRING_MTHD          VARCHAR2(20) NULL ,
	SO_NM                VARCHAR2(100) NULL ,
	SO_EML               VARCHAR2(100) NULL ,
	CIO_ADMN_NM          VARCHAR2(100) NULL ,
	CIO_ADMN_EML         VARCHAR2(100) NULL ,
	HRO_SPC_NM           VARCHAR2(100) NULL ,
	HRO_SPC_EML          VARCHAR2(100) NULL ,
	CLA_SPC_NM           VARCHAR2(100) NULL ,
	CLA_SPC_EML          VARCHAR2(100) NULL ,
	COM_CHR_NM           VARCHAR2(100) NULL ,
	COM_CHR_EML          VARCHAR2(100) NULL ,
	COM_CHR_ORG_NM       VARCHAR2(200) NULL ,
	SME_RQRD             VARCHAR2(10) NULL ,
	STFFNG_NEED_VLDTD    VARCHAR2(10) NULL ,
	JSTFCTN_NOT_VLD_STAFF_ND VARCHAR2(4000) NULL ,
	HIRING_OPT_GUIDE_RVWD VARCHAR2(10) NULL ,
	JSTFCTN_NOT_RVWNG_HR_OPT_GD VARCHAR2(4000) NULL ,
    REQ_APPRVD_BY_HHS   VARCHAR2(10) NULL ,
    JSTFCTN_NOT_RCVNG_HHS_APPRL VARCHAR2(4000) NULL ,
	POS_BSD_MGMT_SYS_NO  VARCHAR2(100) NULL 
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPK_RECRUITMENT ON HHS_CDC_HR.RECRUITMENT
(CASE_ID   ASC);



CREATE TABLE HHS_CDC_HR.VALIDATION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	PRE_RECRUITMENT_MTNG_DT VARCHAR2(20) NULL ,
	PPP_PCP_CLRD         VARCHAR2(10) NULL ,
	PPP_PCP_CLRD_DT              VARCHAR2(20) NULL ,
	JUSTFCTN_PPP_PCP_NOT_CLEARED             VARCHAR2(4000) NULL 
);



CREATE UNIQUE INDEX HHS_CDC_HR.XPK_VALIDATION ON HHS_CDC_HR.VALIDATION
(CASE_ID   ASC);

