--------------------------------------------------------
--  File created - Thursday-April-05-2018   
--------------------------------------------------------
REM INSERTING into HHS_CDC_HR.EXTERNAL_LINK_LOOKUP
SET DEFINE OFF;
Insert into HHS_CDC_HR.EXTERNAL_LINK_LOOKUP (LINK_ID,LINK_GROUP,LINK_URL,LINK_DISPLAY,LINK_DESCRIPTION,LINK_ACTIVE,LINK_EFFECTIVE_DT,LINK_EXPIRATION_DT,LINK_DISP_ORDER) values (6,'TITLE5_RESOURCES_CLASSIFICATIONONLY','https://www.opm.gov/policy-data-oversight/classification-qualifications/classifying-general-schedule-positions/#url=Overview','OPM Classification Standards','The Standards provide general information used in determining the occupational series, title, grade, and pay system for positions performing white collar work in the Federal Government.','1',null,null,6);
Insert into HHS_CDC_HR.EXTERNAL_LINK_LOOKUP (LINK_ID,LINK_GROUP,LINK_URL,LINK_DISPLAY,LINK_DESCRIPTION,LINK_ACTIVE,LINK_EFFECTIVE_DT,LINK_EXPIRATION_DT,LINK_DISP_ORDER) values (2,'COMMON_RESOURCES','http://pbms.cdc.gov','Position-Based Management System (PBMS)','PBMS provides information to CDC''s Integrated Resources Information System (IRIS) Staffing for budget planning purposes and also supports CDC''s Enterprise Hiring Plan.','1',null,null,2);
Insert into HHS_CDC_HR.EXTERNAL_LINK_LOOKUP (LINK_ID,LINK_GROUP,LINK_URL,LINK_DISPLAY,LINK_DESCRIPTION,LINK_ACTIVE,LINK_EFFECTIVE_DT,LINK_EXPIRATION_DT,LINK_DISP_ORDER) values (3,'TITLE5_RESOURCES','https://nccdintra.cdc.gov/ORG/Default/Default.aspx','Position Description (PD) Library','A database of established Position Descriptions that have already been classified and approved by HRO and assigned to the vacated positions.','1',null,null,3);
Insert into HHS_CDC_HR.EXTERNAL_LINK_LOOKUP (LINK_ID,LINK_GROUP,LINK_URL,LINK_DISPLAY,LINK_DESCRIPTION,LINK_ACTIVE,LINK_EFFECTIVE_DT,LINK_EXPIRATION_DT,LINK_DISP_ORDER) values (4,'COMMON_RESOURCES','https://srts.cdc.gov','Strategic Recruitment Tracking System (SRTS)','Grants the hiring official or hiring staff member, access to find potential non-competitive candidates such as Schedule A, VRA/VEOA, direct hire, Reinstatement eligible, etc. SRTS contains resumes of people who provided their resumes to CDC at recruitment and outreach events. SRTS also contains information on CDCs participation in recruitment events, conferences, and college or university visits.','1',null,null,4);
Insert into HHS_CDC_HR.EXTERNAL_LINK_LOOKUP (LINK_ID,LINK_GROUP,LINK_URL,LINK_DISPLAY,LINK_DESCRIPTION,LINK_ACTIVE,LINK_EFFECTIVE_DT,LINK_EXPIRATION_DT,LINK_DISP_ORDER) values (5,'TITLE42_RESOURCES','http://www.cdc.com','Statement of Duties (SOD) library','**TBD SOD Description**','0',null,null,5);
Insert into HHS_CDC_HR.EXTERNAL_LINK_LOOKUP (LINK_ID,LINK_GROUP,LINK_URL,LINK_DISPLAY,LINK_DESCRIPTION,LINK_ACTIVE,LINK_EFFECTIVE_DT,LINK_EXPIRATION_DT,LINK_DISP_ORDER) values (1,'COMMON_RESOURCES','http://intranet.cdc.gov/od/hcrmo/html/hcrmo/wrt/implement-reshaping-option.html#implementation','Hiring Options Guide','Provides hiring options, or hiring authorities, which are regulatory requirements under which certain individuals are eligible to be hired.','1',null,null,1);
