------------------------------------------------------------------------------------------
--  Name	            : 	CDC_8_grant_cdc_hr.sql
--	Author				:	Taeho Lee <thee@bizflow.com>
--	
--	Project				:	HHS CDC HR Workflow Solution - EWITS 2.0
--	Purpose				:	Grant permission to roles in HHS_CDC_HR database schema
--	
--  Notes               :   Run on HHS_CDC_HR schema
--
-- 	WHEN		WHO			WHAT		
-- 	-----------	--------	-------------------------------------------------------
-- 	11/14/2018	THLEE		Created
------------------------------------------------------------------------------------------
set define off;

--set serveroutput on;
BEGIN
	FOR ATAB IN (SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'HHS_CDC_HR' ORDER BY TABLE_NAME ) LOOP
        --DBMS_OUTPUT.PUT_LINE('GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.'||ATAB.TABLE_NAME||' TO HHS_CDC_HR_DEV_ROLE;');
		EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.'||ATAB.TABLE_NAME||' TO HHS_CDC_HR_DEV_ROLE';
        --DBMS_OUTPUT.PUT_LINE('GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.'||ATAB.TABLE_NAME||' TO HHS_CDC_HR_RW_ROLE;');
        EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.'||ATAB.TABLE_NAME||' TO HHS_CDC_HR_RW_ROLE';
	END LOOP;
END;
/

BEGIN
	FOR AFUNC IN (SELECT OBJECT_NAME FROM ALL_OBJECTS WHERE OWNER = 'HHS_CDC_HR' AND OBJECT_TYPE = 'FUNCTION' ORDER BY OBJECT_NAME ) LOOP
        --DBMS_OUTPUT.PUT_LINE('GRANT EXECUTE ON HHS_CDC_HR.'||AFUNC.OBJECT_NAME||' TO HHS_CDC_HR_DEV_ROLE;');
		EXECUTE IMMEDIATE 'GRANT EXECUTE ON HHS_CDC_HR.'||AFUNC.OBJECT_NAME||' TO HHS_CDC_HR_DEV_ROLE';
        --DBMS_OUTPUT.PUT_LINE('GRANT EXECUTE ON HHS_CDC_HR.'||AFUNC.OBJECT_NAME||' TO HHS_CDC_HR_RW_ROLE;');
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON HHS_CDC_HR.'||AFUNC.OBJECT_NAME||' TO HHS_CDC_HR_RW_ROLE';
	END LOOP;
END;
/

BEGIN
	FOR ASP IN (SELECT OBJECT_NAME FROM ALL_OBJECTS WHERE OWNER = 'HHS_CDC_HR' AND OBJECT_TYPE = 'PROCEDURE' ORDER BY OBJECT_NAME ) LOOP
        --DBMS_OUTPUT.PUT_LINE('GRANT EXECUTE ON HHS_CDC_HR.'||ASP.OBJECT_NAME||' TO HHS_CDC_HR_DEV_ROLE;');
		EXECUTE IMMEDIATE 'GRANT EXECUTE ON HHS_CDC_HR.'||ASP.OBJECT_NAME||' TO HHS_CDC_HR_DEV_ROLE';
        --DBMS_OUTPUT.PUT_LINE('GRANT EXECUTE ON HHS_CDC_HR.'||ASP.OBJECT_NAME||' TO HHS_CDC_HR_RW_ROLE;');
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON HHS_CDC_HR.'||ASP.OBJECT_NAME||' TO HHS_CDC_HR_RW_ROLE';
	END LOOP;
END;
/



/*
--Grant Functions
GRANT EXECUTE ON HHS_CDC_HR.FN_CONCAT_HR_RECORDS TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_CONCAT_HR_RECORDS TO HHS_CDC_HR_RW_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.FN_PARSENAME TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_PARSENAME TO HHS_CDC_HR_RW_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.FN_GET_ACT_CMPLTUSR TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_GET_ACT_CMPLTUSR TO HHS_CDC_HR_RW_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.FN_GET_FORM_DATA_FIELD_VALUE TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_GET_FORM_DATA_FIELD_VALUE TO HHS_CDC_HR_RW_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.FN_GET_LOOKUP_LABEL TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_GET_LOOKUP_LABEL TO HHS_CDC_HR_RW_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.FN_GET_LOOKUP_LABEL_BY_NAME TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_GET_LOOKUP_LABEL_BY_NAME TO HHS_CDC_HR_RW_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.FN_GET_XML_FIELD_VALUE TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_GET_XML_FIELD_VALUE TO HHS_CDC_HR_RW_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.FN_GET_XML_NODE_VALUE TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_GET_XML_NODE_VALUE TO HHS_CDC_HR_RW_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.FN_GET_XML_VALUE TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.FN_GET_XML_VALUE TO HHS_CDC_HR_RW_ROLE;
/
*/    

/*
--Grant Stored Procedure
GRANT EXECUTE ON HHS_CDC_HR.SP_CLEAN_FORM_RECORDS TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_CLEAN_FORM_RECORDS TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.SP_ERROR_LOG TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_ERROR_LOG TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_APPOINTMENT_TBLS TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_APPOINTMENT_TBLS TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_CLASSIFICATION_TBLS TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_CLASSIFICATION_TBLS TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_NAMEDACTION_TBLS TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_NAMEDACTION_TBLS TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_RECRUITMENT_TBLS TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_RECRUITMENT_TBLS TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_TRIAGE_TBLS TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_TRIAGE_TBLS TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_FORM_DATA TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_UPDATE_FORM_DATA TO HHS_CDC_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CDC_HR.SP_DATACOPY_FORM_DATA TO HHS_CDC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CDC_HR.SP_DATACOPY_FORM_DATA TO HHS_CDC_HR_DEV_ROLE;
/
*/

