
--------------------------------------------------------------
--DROP TABLE HHS_CDC_HR.ERA_LOG_CAPHR_PAR;
DROP TABLE ERA_LOG_CAPHR_PAR;
CREATE TABLE HHS_CDC_HR.ERA_LOG_CAPHR_PAR
(
    ID                          INTEGER NOT NULL
    ,EMPLID                     VARCHAR2(100)
    ,ADMIN_CODE                 VARCHAR2(100)
    ,PAR_ACTION                 VARCHAR2(100)
    ,PAR_ACTION_REASON          VARCHAR2(100)
    ,PAR_STATUS                 VARCHAR2(100)
    ,GVT_EFFDT                  DATE
    ,GVT_EFFDT_PROPOSED_DT      DATE
    ,PROCID                     INTEGER
    ,ERA_STATUS                 VARCHAR2(100)
    ,DSCRPTN                    VARCHAR2(4000)
    ,CREATIONDTIME              TIMESTAMP
);


ALTER TABLE HHS_CDC_HR.ERA_LOG_CAPHR_PAR ADD CONSTRAINT ERA_LOG_CAPHR_PAR_PK PRIMARY KEY (ID);
/

CREATE INDEX HHS_CDC_HR.ERA_LOG_CAPHR_PAR_NK1 ON HHS_CDC_HR.ERA_LOG_CAPHR_PAR (EMPLID, ADMIN_CODE, PAR_ACTION, PAR_ACTION_REASON, PAR_STATUS, GVT_EFFDT, GVT_EFFDT_PROPOSED_DT);
/

CREATE SEQUENCE HHS_CDC_HR.ERA_LOG_CAPHR_PAR_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
/

CREATE OR REPLACE TRIGGER HHS_CDC_HR.ERA_LOG_CAPHR_PAR_BIR
BEFORE INSERT ON HHS_CDC_HR.ERA_LOG_CAPHR_PAR
FOR EACH ROW
BEGIN
	SELECT ERA_LOG_CAPHR_PAR_SEQ.NEXTVAL
	INTO :NEW.ID
	FROM DUAL;
END;
/

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ERA_LOG_CAPHR_PAR TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ERA_LOG_CAPHR_PAR TO HHS_CDC_HR_DEV_ROLE;
/

