CREATE TABLE CAPHR_INFO
(
	CASE_ID              NUMBER(10) NOT NULL ,
	CAPHR_RMRKS          VARCHAR2(4000) NULL 
);

CREATE UNIQUE INDEX XPKCapHR_INFO ON CAPHR_INFO
(CASE_ID   ASC);

ALTER TABLE CAPHR_INFO
	ADD CONSTRAINT  XPKCapHR_INFO PRIMARY KEY (CASE_ID);
/

CREATE TABLE NAMED_ACTION
(
	CASE_ID              NUMBER(10) NOT NULL ,
	PAR_ACTN             VARCHAR2(200) NULL ,
	PAR_ACTN_TP          VARCHAR2(200) NULL ,
	PRPSD_EFFCTV_DT      VARCHAR2(20) NULL ,
	EMPL_ID              VARCHAR2(200) NULL ,
	EMPL_NM              VARCHAR2(200) NULL ,
	PRE_CNSLTTN_REQD     VARCHAR2(10) NULL ,
	NA_MTNG_DT           VARCHAR2(20) NULL 
);



CREATE UNIQUE INDEX XPKNamed_Acttion ON NAMED_ACTION
(CASE_ID   ASC);



ALTER TABLE NAMED_ACTION
	ADD CONSTRAINT  XPKNamed_Acttion PRIMARY KEY (CASE_ID);
/
