--SELECT MAX(TBL_ID) FROM HHS_CDC_HR.TBL_LOOKUP;

DELETE FROM HHS_CDC_HR.TBL_LOOKUP
WHERE TBL_LTYPE IN ('StartStop', 'ATCCitizen', 'DaysHours', 'EntitledBenefits')
;

INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13700,'StartStop','Start','Start',1,1);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13701,'StartStop','Stop','Stop',1,2);

INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13750,'ATCCitizen','United States of America (USA)','United States of America (USA)',1,1);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13751,'ATCCitizen','United States of America (USA)','United States of America (USA)',1,2);

INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13800,'DaysHours','Days','Days',1,1);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13801,'DaysHours','Hours','Hours',1,2);

INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13850,'EntitledBenefits','FEHB','FEHB',1,1);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13851,'EntitledBenefits','FGELI','FGELI',1,2);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13852,'EntitledBenefits','FGELI','FGELI',1,2);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13853,'EntitledBenefits','Retirement','Retirement',1,3);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13854,'EntitledBenefits','TSP','TSP',1,4);

COMMIT;
/
