
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13700,'StartStop','Start','Start',1,1);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13701,'StartStop','Stop','Stop',1,2);

INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13750,'ATCCitizen','United States of America (USA)','United States of America (USA)',1,1);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13751,'ATCCitizen','Other','Other',1,2);

INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13800,'DaysHours','Days','Days',1,1);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13801,'DaysHours','Hours','Hours',1,2);

INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13850,'EntitledBenefits','FEHB','FEHB',1,1);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13851,'EntitledBenefits','FGELI','FGELI',1,2);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13852,'EntitledBenefits','FGELI','FGELI',1,2);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13853,'EntitledBenefits','Retirement','Retirement',1,3);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13854,'EntitledBenefits','TSP','TSP',1,4);

INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13900,'PenRejAppNA','Pending','Pending',1,1);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13901,'PenRejAppNA','Rejected','Rejected',1,2);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13902,'PenRejAppNA','Approved','Approved',1,3);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13902,'PenRejAppNA','N/A','N/A',1,3);

INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13950,'PenRejApp','Pending','Pending',1,1);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13951,'PenRejApp','Rejected','Rejected',1,2);
INSERT INTO HHS_CDC_HR.TBL_LOOKUP (TBL_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER)
VALUES (13952,'PenRejApp','Approved','Approved',1,3);


UPDATE HHS_CDC_HR.external_link_lookup
SET LINK_URL = 'https://atpv-nifm-web1.cdc.gov/PDLibrary/'
WHERE LINK_ID = 3;
