/*
 * Copyright (C) BizFlow Corp - All Rights Reserved
 *
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 *
 * Written by Tae Ho Lee <thlee@bizflow.com> <Taeho.BPM@gmail.com>, 4/2018
 *
 */

package com.bizflow.drools.document.rules;

import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map
import java.util.Iterator
import java.util.Arrays

import com.bizflow.ps.drools.document.model.WorkflowDocument;
import com.bizflow.ps.drools.document.model.WorkflowRuleSearch;
import com.bizflow.ps.drools.document.model.WorkflowField;

dialect "mvel"

function void addDocument(ArrayList bizflowDocument, String documentName, boolean required) {
    System.out.println("RULE R1>> addDocument");
    bizflowDocument.add(new WorkflowDocument(bizflowDocument.size() + 1, documentName, bizflowDocument.size()+1, required));
}

function void addDocumentEx(ArrayList bizflowDocument, String documentName, String actName, String[] actNames, boolean required) {
    System.out.println("RULE R1>> addDocumentEx");
    boolean isRequiredDocument = false;
    for (String act: actNames) {
        System.out.println("RULE R1>> actName=" + actName + ", act=" + act);
        if (act.equals(actName)) {
            isRequiredDocument = required;
            break;
        }
    }
    System.out.println("RULE R1>> addDocumentEx=" + isRequiredDocument);
    bizflowDocument.add(new WorkflowDocument(bizflowDocument.size() + 1, documentName, bizflowDocument.size()+1, isRequiredDocument));
}
/*
function void addDocuments(ArrayList bizflowDocument, BizFlowProcess proc, List allDocuments) {
    for (Object document : allDocuments) {
        addDocument(bizflowDocument, (String)document, false);
    }
}
*/

/*
Process / Activity Names as of April 13, 2018

    Recruitment
        Identify Staffing Need
        Prepare Pre-Recruitment Documents
        Finalize the Pre-Recruitment Checklist
        Validate Recruitment
        First Step of Recruitment

    Classification
        Submit PD/SOD for Classification
        Classify PD/SOD
        Provide Concurrence on Classification
        Finalize Classification
        Provide Additional Concurrence on Classification
*/

/*----------------------------------------------------------------------------------------------------
    Recruitment Process Rules:
----------------------------------------------------------------------------------------------------*/
rule "Recruitment / Identify Staffing Need / *"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Identify Staffing Need",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue in ("Title 5", "Title 42", "SES/SL/ST", "")								
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R1>> " + $docSearch);
end

//------
rule "Recruitment / Prepare Pre-Recruitment Documents / Hiring Method = Title 5"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Prepare Pre-Recruitment Documents",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R2>> " + $docSearch);
        addDocument($workflowDocuments, "OF-8", true);
        addDocument($workflowDocuments, "Position Description", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
end

rule "Recruitment / Prepare Pre-Recruitment Documents / Hiring Method = Title 42"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Prepare Pre-Recruitment Documents",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R3>> " + $docSearch);
        addDocument($workflowDocuments, "Position Sensitivity Form", true);
        addDocument($workflowDocuments, "Statement of Duties", true);
end

rule "Recruitment / Prepare Pre-Recruitment Documents / Hiring Method = SES/SL/ST"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Prepare Pre-Recruitment Documents",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "SES/SL/ST"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R4>> " + $docSearch);
        addDocument($workflowDocuments, "OF-8", true);
        addDocument($workflowDocuments, "Statement of Duties", true);
end
	
rule "Recruitment / Prepare Pre-Recruitment Documents / Hiring Method = All Others"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Prepare Pre-Recruitment Documents",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue not in ("Title 5", "Title 42", "SES/SL/ST", "")
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R5>> " + $docSearch);
        addDocument($workflowDocuments, "OF-8", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "PD Coversheet", true);
        addDocument($workflowDocuments, "Position Description", true);
end

//------
rule "Recruitment / Finalize the Pre-Recruitment Checklist / Hiring Method = Title 5"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Finalize the Pre-Recruitment Checklist",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R6>> " + $docSearch);
        addDocument($workflowDocuments, "OF-8", true);
        addDocument($workflowDocuments, "Position Description", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "Job Analysis Workbook", true);
end

rule "Recruitment / Finalize the Pre-Recruitment Checklist / Hiring Method = Title 42"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Finalize the Pre-Recruitment Checklist",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R7>> " + $docSearch);
        addDocument($workflowDocuments, "Position Sensitivity Form", true);
        addDocument($workflowDocuments, "Statement of Duties", true);
        addDocument($workflowDocuments, "Job Analysis Workbook", true);
end

rule "Recruitment / Finalize the Pre-Recruitment Checklist / Hiring Method = SES/SL/ST"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Finalize the Pre-Recruitment Checklist",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "SES/SL/ST"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R8>> " + $docSearch);
        addDocument($workflowDocuments, "OF-8", true);
        addDocument($workflowDocuments, "Position Description", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "Job Analysis Workbook", true);
        addDocument($workflowDocuments, "Specialized Experience Statement", true);
        addDocument($workflowDocuments, "Crediting Plan", true);        
end

rule "Recruitment / Finalize the Pre-Recruitment Checklist / Hiring Method = All Others"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Finalize the Pre-Recruitment Checklist",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue not in ("Title 5", "Title 42", "SES/SL/ST", "")
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R9>> " + $docSearch);
        addDocument($workflowDocuments, "OF-8", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "PD Coversheet", true);
        addDocument($workflowDocuments, "Position Description", true);
end

//------
rule "Recruitment / Validate Recruitment / Hiring Method = Title 5"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Validate Recruitment",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R10>> " + $docSearch);
        addDocument($workflowDocuments, "OF-8", true);
        addDocument($workflowDocuments, "Position Description", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "Job Analysis Workbook", true);
        addDocument($workflowDocuments, "PPP/PCP-related document", true);        
end

rule "Recruitment / Validate Recruitment / Hiring Method = Title 42"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Validate Recruitment",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R11>> " + $docSearch);
        addDocument($workflowDocuments, "Position Sensitivity Form", true);
        addDocument($workflowDocuments, "Statement of Duties", true);
        addDocument($workflowDocuments, "Job Analysis Workbook", true);
end

rule "Recruitment / Validate Recruitment / Hiring Method = SES/SL/ST"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Validate Recruitment",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "SES/SL/ST"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R12>> " + $docSearch);
        addDocument($workflowDocuments, "OF-8", true);
        addDocument($workflowDocuments, "Position Description", true);
        addDocument($workflowDocuments, "Job Analysis Workbook", true);
end

rule "Recruitment / Validate Recruitment / Hiring Method = All Others"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Validate Recruitment",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue not in ("Title 5", "Title 42", "SES/SL/ST", "")
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R13>> " + $docSearch);
        addDocument($workflowDocuments, "OF-8", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "PD Coversheet", true);
        addDocument($workflowDocuments, "Position Description", true);
end

//------
rule "Recruitment / Track USA Staffing Status / Hiring Method = Title 5"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Track USA Staffing Status",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R14>> " + $docSearch);
        addDocument($workflowDocuments, "OF-8", true);
        addDocument($workflowDocuments, "Position Description", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "Job Analysis Workbook", true);
end

rule "Recruitment / Track USA Staffing Status / Hiring Method = Title 42"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Track USA Staffing Status",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R15>> " + $docSearch);
        addDocument($workflowDocuments, "Position Sensitivity Form", true);
        addDocument($workflowDocuments, "Statement of Duties", true);
        addDocument($workflowDocuments, "Job Analysis Workbook", true);
end

rule "Recruitment / Track USA Staffing Status / Hiring Method = SES/SL/ST"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Track USA Staffing Status",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "SES/SL/ST"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R16>> " + $docSearch);
        addDocument($workflowDocuments, "OF-8", true);
        addDocument($workflowDocuments, "Position Description", true);
        addDocument($workflowDocuments, "Job Analysis Workbook", true);
end

rule "Recruitment / Track USA Staffing Status / Hiring Method = All Others"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Recruitment",
                            actName == "Track USA Staffing Status",
                            $actName : actName, $fields : fields
                        )

        $field      :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue not in ("Title 5", "Title 42", "SES/SL/ST", "")
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE R17>> " + $docSearch);
        addDocument($workflowDocuments, "OF-8", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "PD Coversheet", true);
        addDocument($workflowDocuments, "Position Description", true);
end

/*----------------------------------------------------------------------------------------------------
    Classification Process Rules:
----------------------------------------------------------------------------------------------------*/

//----------

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = New, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C1>> " + $docSearch);
        addDocument($workflowDocuments, "Position Description", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = New, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C2>> " + $docSearch);
        addDocument($workflowDocuments, "Position Description", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = New, RequestType = Appointment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C3>> " + $docSearch);
        addDocument($workflowDocuments, "Position Description", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = 5 Year Recertificaton, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "5 Year Recertificaton"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C4>> " + $docSearch);
        addDocument($workflowDocuments, "Realignment Spreadsheet", true);
        addDocument($workflowDocuments, "Justification", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "Staffing List", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = 5 Year Recertificaton, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "5 Year Recertificaton"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C5>> " + $docSearch);
        addDocument($workflowDocuments, "Realignment Spreadsheet", true);
        addDocument($workflowDocuments, "Justification", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "Staffing List", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = 5 Year Recertificaton, RequestType = Appointment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "5 Year Recertificaton"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C6>> " + $docSearch);
        addDocument($workflowDocuments, "Realignment Spreadsheet", true);
        addDocument($workflowDocuments, "Justification", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "Staffing List", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = BUS Code Change, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "BUS Code Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C7>> " + $docSearch);
        addDocument($workflowDocuments, "Position Description", true);
        addDocument($workflowDocuments, "Justification", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = BUS Code Change, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "BUS Code Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C8>> " + $docSearch);
        addDocument($workflowDocuments, "Position Description", true);
        addDocument($workflowDocuments, "Justification", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = BUS Code Change, RequestType = Appointment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "BUS Code Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C9>> " + $docSearch);
        addDocument($workflowDocuments, "Position Description", true);
        addDocument($workflowDocuments, "Justification", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Duty Station Change, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Duty Station Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C10>> " + $docSearch);
        addDocument($workflowDocuments, "Current PD", true);
        addDocument($workflowDocuments, "Current OF8", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Duty Station Change, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Duty Station Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C11>> " + $docSearch);
        addDocument($workflowDocuments, "Current PD", true);
        addDocument($workflowDocuments, "Current OF8", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Duty Station Change, RequestType = Appointment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Duty Station Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C12>> " + $docSearch);
        addDocument($workflowDocuments, "Current PD", true);
        addDocument($workflowDocuments, "Current OF8", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = FLSA Request Change, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "FLSA Request Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C13>> " + $docSearch);
        addDocument($workflowDocuments, "Current PD", true);
        addDocument($workflowDocuments, "Current OF8", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = FLSA Request Change, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "FLSA Request Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C14>> " + $docSearch);
        addDocument($workflowDocuments, "Current PD", true);
        addDocument($workflowDocuments, "Current OF8", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = FLSA Request Change, RequestType = Appointment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "FLSA Request Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C15>> " + $docSearch);
        addDocument($workflowDocuments, "Current PD", true);
        addDocument($workflowDocuments, "Current OF8", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Financial Statement Request Change, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Financial Statement Request Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C16>> " + $docSearch);
        addDocument($workflowDocuments, "Current PD", true);
        addDocument($workflowDocuments, "Current OF8", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Financial Statement Request Change, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Financial Statement Request Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C17>> " + $docSearch);
        addDocument($workflowDocuments, "Current PD", true);
        addDocument($workflowDocuments, "Current OF8", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Financial Statement Request Change, RequestType = Appointment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Financial Statement Request Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C18>> " + $docSearch);
        addDocument($workflowDocuments, "Current PD", true);
        addDocument($workflowDocuments, "Current OF8", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Incumbency Only Position, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Incumbency Only Position"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C19>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Incumbency Only Position, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Incumbency Only Position"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C20>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Incumbency Only Position, RequestType = Appointment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Incumbency Only Position"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C21>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Position Sensitivity Change, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Position Sensitivity Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C22>> " + $docSearch);
        addDocument($workflowDocuments, "Current PD", true);
        addDocument($workflowDocuments, "Current OF8", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Position Sensitivity Change, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Position Sensitivity Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C23>> " + $docSearch);
        addDocument($workflowDocuments, "Current PD", true);
        addDocument($workflowDocuments, "Current OF8", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Position Sensitivity Change, RequestType = Appointment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Position Sensitivity Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C24>> " + $docSearch);
        addDocument($workflowDocuments, "Current PD", true);
        addDocument($workflowDocuments, "Current OF8", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Position Title and Series Change, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Position Title and Series Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C25>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Position Title and Series Change, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Position Title and Series Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C26>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Position Title and Series Change, RequestType = Appointment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Position Title and Series Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C27>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Position Upgrade Request, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Position Upgrade Request"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C28>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Position Upgrade Request, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Position Upgrade Request"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C29>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Position Upgrade Request, RequestType = Appointment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Position Upgrade Request"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C30>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Realignment, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Realignment"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C31>> " + $docSearch);
        addDocument($workflowDocuments, "Realignment Spreadsheet", true);
        addDocument($workflowDocuments, "Reorganization Aproval Letter", false);        
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Realignment, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Realignment"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C32>> " + $docSearch);
        addDocument($workflowDocuments, "Realignment Spreadsheet", true);
        addDocument($workflowDocuments, "Reorganization Aproval Letter", false);        
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Realignment, RequestType = Appointment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Realignment"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C33>> " + $docSearch);
        addDocument($workflowDocuments, "Realignment Spreadsheet", true);
        addDocument($workflowDocuments, "Reorganization Aproval Letter", false);        
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Repurposed, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Repurposed"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C34>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Repurposed, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Repurposed"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C35>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Repurposed, RequestType = Appointment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Repurposed"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C36>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Revision, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Revision"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C37>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Revision, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Revision"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C38>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Revision, RequestType = Appointment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Revision"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C39>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Supervisory Code Change, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Supervisory Code Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C40>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Supervisory Code Change, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Supervisory Code Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C41>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Supervisory Code Change, RequestType = Appointment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Supervisory Code Change"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE C42>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Based Org Chart", true);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Other, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Other"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C43>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Sensitivity Form", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "List of Subordinates", false);
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Other, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Other"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C44>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Sensitivity Form", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "List of Subordinates", false);        
end

rule "Classification / Rule HiringMethod = Title 5, SubmissionReason = Other, RequestType = Appointment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 5"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "Other"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C45>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Position Sensitivity Form", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "List of Subordinates", false);        
end

rule "Classification / Rule HiringMethod = Title 42, SubmissionReason = New, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C46>> " + $docSearch);
        addDocument($workflowDocuments, "Statement of Duties", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);        
end

rule "Classification / Rule HiringMethod = Title 42, SubmissionReason = New, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C47>> " + $docSearch);
        addDocument($workflowDocuments, "Statement of Duties", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
end

rule "Classification / Rule HiringMethod = Title 42, SubmissionReason = New, RequestType = Classification Only, and EmployeeType = SBRS"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == "SBRS"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C48>> " + $docSearch);
        addDocument($workflowDocuments, "Statement of Duties", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 42, SubmissionReason = New, RequestType = Recruitment with Classification, and EmployeeType = SBRS"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == "SBRS"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C49>> " + $docSearch);
        addDocument($workflowDocuments, "Statement of Duties", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
end

rule "Classification / Rule HiringMethod = Title 42, SubmissionReason = New, RequestType = Appointment with Classification, and EmployeeType = SBRS"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == "SBRS"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C50>> " + $docSearch);
        addDocument($workflowDocuments, "Statement of Duties", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
end

rule "Classification / Rule HiringMethod = Title 42, SubmissionReason = New, RequestType = Classification Only, and EmployeeType = Distinguished Consultant"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == "Distinguished Consultant"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C51>> " + $docSearch);
        addDocument($workflowDocuments, "Statement of Duties", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);        
end

rule "Classification / Rule HiringMethod = Title 42, SubmissionReason = New, RequestType = Recruitment with Classification, and EmployeeType = Distinguished Consultant"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == "Distinguished Consultant"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C52>> " + $docSearch);
        addDocument($workflowDocuments, "Statement of Duties", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
end

rule "Classification / Rule HiringMethod = Title 42, SubmissionReason = New, RequestType = Appointment with Classification, and EmployeeType = Distinguished Consultant"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == "Distinguished Consultant"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C53>> " + $docSearch);
        addDocument($workflowDocuments, "Statement of Duties", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
end

rule "Classification / Rule HiringMethod = Title 42, SubmissionReason = New, RequestType = Classification Only, and EmployeeType = FTE"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == "FTE"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C54>> " + $docSearch);
        addDocument($workflowDocuments, "Statement of Duties", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);        
end

rule "Classification / Rule HiringMethod = Title 42, SubmissionReason = New, RequestType = Recruitment with Classification, and EmployeeType = FTE"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == "FTE"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C55>> " + $docSearch);
        addDocument($workflowDocuments, "Statement of Duties", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
end

rule "Classification / Rule HiringMethod = Title 42, SubmissionReason = New, RequestType = Appointment with Classification, and EmployeeType = FTE "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        ) 

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == "FTE"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C56>> " + $docSearch);
        addDocument($workflowDocuments, "Pre-Recruitment Consultation Worksheet", true);
        addDocument($workflowDocuments, "CDC 0.1475 Fellowship Program Request", true);
        addDocument($workflowDocuments, "Resume", true);
        addDocument($workflowDocuments, "Position Sensitivity Level Designation Form", true);
        addDocument($workflowDocuments, "Original Transcripts", true);
        addDocument($workflowDocuments, "Two Letters of Recommendation", true);
        addDocument($workflowDocuments, "Statement of Duties", true);
        addDocument($workflowDocuments, "Foreign Education Equivalency when applicable", false);
        addDocument($workflowDocuments, "Email from PHIO/OSSAM certifying prescreen for all non-citizens", false);
        addDocument($workflowDocuments, "Fellowship Service Agreement For Travel and Transportation Expenses", false);
        addDocument($workflowDocuments, "CIO Peer Review Board Concurrence", false);        
end

rule "Classification / Rule HiringMethod = Title 42, SubmissionReason = New, RequestType = Classification Only, and EmployeeType = Non-FTE"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == "Non-FTE"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C57>> " + $docSearch);
        addDocument($workflowDocuments, "Statement of Duties", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = Title 42, SubmissionReason = New, RequestType = Recruitment with Classification, and EmployeeType = Non-FTE"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == "Non-FTE"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C58>> " + $docSearch);
        addDocument($workflowDocuments, "Statement of Duties", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
end

rule "Classification / Rule HiringMethod = Title 42, SubmissionReason = New, RequestType = Appointment with Classification, and EmployeeType = Non-FTE "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "Title 42"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == "Non-FTE"
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C59>> " + $docSearch);
        addDocument($workflowDocuments, "Pre-Recruitment Consultation Worksheet", true);
        addDocument($workflowDocuments, "CDC 0.1475 Fellowship Program Request", true);
        addDocument($workflowDocuments, "Resume", true);
        addDocument($workflowDocuments, "Position Sensitivity Level Designation Form", true);
        addDocument($workflowDocuments, "Statement of Duties must indicate RF will receive training", true);
        addDocument($workflowDocuments, "Original Transcripts", true);
        addDocument($workflowDocuments, "Letter of recommendation from a public or other non-profit institution", true);
        addDocument($workflowDocuments, "Foreign Education Equivalency when applicable", false);
        addDocument($workflowDocuments, "Fellowship Service Agreement For Travel and Transportation Expenses", false);
end

rule "Classification / Rule HiringMethod = SES/SL/ST, SubmissionReason = New, RequestType = Classification Only, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "SES/SL/ST"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Classification Only"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C60>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
        addDocument($workflowDocuments, "Position Review Worksheet", true);
end

rule "Classification / Rule HiringMethod = SES/SL/ST, SubmissionReason = New, RequestType = Recruitment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "SES/SL/ST"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Recruitment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C61>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
end

rule "Classification / Rule HiringMethod = SES/SL/ST, SubmissionReason = New, RequestType = Appointment with Classification, and EmployeeType = "
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",
                            procName == "Classification",
                            $fields : fields
                        )

        $fieldHM    :   ( WorkflowField
                            (
                                fieldId == "HiringMethod",
                                fieldValue == "SES/SL/ST"
                            ) from $fields
                        )

        $fieldSR    :   ( WorkflowField
                            (
                                fieldId == "SubmissionReason",
                                fieldValue == "New"
                            ) from $fields
                        )

        $fieldRT    :   ( WorkflowField
                            (
                                fieldId == "RequestType",
                                fieldValue == "Appointment with Classification"
                            ) from $fields
                        )

        $fieldET    :   ( WorkflowField
                            (
                                fieldId == "EmployeeType",
                                fieldValue == ""
                            ) from $fields
                        )

        $workflowDocuments : ArrayList()
        
    then
        System.out.println("RULE C62>> " + $docSearch);
        addDocument($workflowDocuments, "Proposed PD", true);
        addDocument($workflowDocuments, "Organizational Chart", true);
end

rule "CDC - Appointment - Resume is a Document Type"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC",                        
                            procName == "Appointment"
                        )

        $workflowDocuments : ArrayList()

    then
        System.out.println("RULE A1>> " + $docSearch);
        addDocument($workflowDocuments, "Resume", true);
end

//------------------------------
// DEFAULT DOCUMENT
//------------------------------
rule "CDC - Classification - Empty"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            tenantID == "CDC"
                        )
        $workflowDocuments : ArrayList()
    then
        System.out.println("RULE DEFAULT>> " + $docSearch);
        addDocument($workflowDocuments, "Other", false);
end
